### ISSUE TITLE
CurlHandler breaks when there is unicode text in the response body

### ISSUE THREAD

**Issue by rtheunissen** [guzzle/guzzle#1325] opened 2015-12-02 00:21 UTC
I'm getting different results when using the `StreamHandler` vs using the `CurlHandler`, and I'm not sure why. The response body contains some Greek lettering, which might be the cause of the problem.

See https://github.com/rtheunissen/guzzle-cache-handler/issues/6

## Reproducing script

```php
<?php

require "vendor/autoload.php";

use GuzzleHttp\Handler\CurlHandler;
use GuzzleHttp\Handler\StreamHandler;
use GuzzleHttp\Client;

function request($handler)
{
    $url = "http://test.fhmp.net/guzzle/guzzle/issues/1325/";

    $params = [
        'tab' => 'Nationwide',
        'curdate1' => '2015-12-03 06:00:00',
        'curdate2' => '2015-12-04 06:00:00'
    ];

    $client = new Client([
        'handler' => $handler,
    ]);

    $response = $client->post($url, [
        'form_params' => $params
    ]);

    return (string) $response->getBody();
}

var_dump(strlen(request(new CurlHandler())));
var_dump(strlen(request(new StreamHandler())));
```

## Output

```
int(458)
int(102753)
```

**Comment by mtdowling** [comment] 2015-12-02 00:28
Maybe the server you're hitting doesn't provide a static response? Have you tried looking at the `debug` output?

Side question: any reason why you're making your caching abstraction a handler and not a middleware? I think it makes more sense as a middleware as it is more composable and can lead much more customized request/response stacks (e.g., cookie handling can be injected at a specific point in the request lifecycle, the `tap

**Comment by rtheunissen** [comment] 2015-12-02 01:05
> Maybe the server you're hitting doesn't provide a static response?

Nope it's the exact same response. If you were to make 100 requests using the stream handler, there would be 100 identical responses.

> Any reason why you're making your caching abstraction a handler and not a middleware?

I remember thinking a lot about this when I created it, going back and forth between the two. Right now off the top of my head I can't remember why I decided to go with a handler. 

See https://gitter.im/guzzle/guzzle?at=55700203777c17d06a13e104

**Comment by mtdowling** [comment] 2015-12-02 01:17
I think you'll need to get the debug output, see what's being sent over the wire, and see if they differ between the two. I think at minimum, you'll see the StreamHandler is sending a Connection: close header.

From the gitter chat:

> Was wondering if someone could help me out with something. I'm trying to cache requests using a Doctrine\Common\Cache\CacheProvider, and I'm not sure if I should be using Middleware or a Handler. Currently 99% done with a working middleware implementation but I'm stuck at what to return when the cache was validated (ie. I have a valid Response on my hands). If I'm storing the resulting Response, how can I have that response be the resolving one? Before 6.0 I was building a key using the URI and request data outside of the client, but to do that now I need access to $options.

Either way works, but I think the more correct approach for Guzzle is to use a middleware for caching. I was hoping to one day write a caching implementation for Guzzle that uses Guzzle 6, deprecating https://github.com/guzzle/cache-subscriber. The approach I would have used is middleware based, but I am super happy that someone else is writing it :)

In order to change which response is the one that resolved to the user, you just need to return a promise that resolves to a Response object. A middleware approach will be very similar to a handler approach: check the cache to see if a response exists for the request and return it if it's valid. In this case, do not invoke the next handler. Otherwise, invoke the next handler, intercept the response it returns, and do caching logic needed after a response is received. The key is that you just chain promises together using `then`, or you could potentially use a coroutine promise if the logic gets tricky. If you need an example of this, let me know.

**Comment by rtheunissen** [comment] 2015-12-02 01:20
> see if a response exists for the request and return it if it's valid. In this case, do not invoke the next handler.

Wouldn't this short circuit other middleware that comes after? Unless I'm misunderstanding how they work. I'm imagining a chain of middleware where each one adjusts the request (or response) and passes it along to the next one in the chain.

**Comment by rtheunissen** [comment] 2015-12-02 01:22
> I was hoping to one day write a caching implementation for Guzzle that uses Guzzle 6

Maybe when (and if) PSR-6 is accepted. It's very difficult to interface otherwise.

**Comment by mtdowling** [comment] 2015-12-02 01:26
Yes, it would intercept any downstream middlewares. That's actually a feature -- the user decides where in the middleware chain caching is done. Typically it would be one of the last things in a middleware stack, but it's up to the user to control how things compose. There are exceptions though -- for example I might want to inject logging between the caching layer and the actual handler that's being invoked. By making the cache a handler and not a middleware, you'd now preclude someone from logging *all* requests via a middleware (e.g., validation requests).

**Comment by kkopachev** [comment] 2015-12-02 02:46
CurlHandler does not set Content-Length header. If you set it manually in the request options even to invalid number, curl will update it and request will return all data.

**Comment by rtheunissen** [comment] 2015-12-02 21:53
I've noticed that the example endpoint in the reproducing script is now producing something else entirely. I've set up and endpoint to produce static results with default headers, and updated the script. However, I can't reproduce the bug anymore. :(

@mtdowling does @kkopachev's comment re: the content length header make sense as a solution? Is that a bug with the CurlHandler or part of the behaviour of curl itself?

**Comment by mtdowling** [comment] 2015-12-06 07:39
Content-Length could be the difference. The StreamHandler requires that the body of the request is loaded into a stream, and therefore it must exhaust a stream, load it into memory, and provide a content-length when uploading data. When using the CurlHandler, it can actually stream data without needing to know the size of the data up front (hence no content-length).

Different adapters will have different capabilities, each with pros and cons. The difference between Content-Length headers in this case is not a bug, but just how the StreamAdapter works.

**Comment by mtdowling** [comment] 2015-12-09 21:33
Closing. Let me know if there's anything else.

**Closed by mtdowling** 2015-12-09 21:33 UTC
