### ISSUE TITLE
Summary of request exception is too short

### ISSUE THREAD

**Issue by pawelryznar** [guzzle/guzzle#2177] opened 2018-10-26 11:16 UTC
In vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:getResponseBodySummary exception message gets truncated. Why so short?

Because of that sometimes we are not able to understand errors in production when we use APIs of external services.

**Comment by gmponos** [comment] 2018-10-31 18:05
Duplicate of 
- https://github.com/guzzle/guzzle/issues/1722
- https://github.com/guzzle/guzzle/issues/2185

**Comment by sagikazarmark** [comment] 2018-10-31 22:54
Closing as duplicate.

**Closed by sagikazarmark** 2018-10-31 22:54 UTC
Labels: resolution/duplicate
