### ISSUE TITLE
Use of undefined constant INTL_IDNA_VARIANT_UTS46 - assumed 'INTL_IDNA_VARIANT_UTS46' (this will throw an Error in a future version of PHP)

### ISSUE THREAD

**Issue by nimeshdixit** [guzzle/guzzle#2457] opened 2019-12-13 12:09 UTC
**Guzzle version(s) affected**: x.y.z
Guzzle version: 6.5
Laravel version: 5.8.*
PHP Version: 7.2

INTL version : 1.1.0
ICU version : 4.2.1

OS : Amazon Linux AMI

![image](https://user-images.githubusercontent.com/50728113/70798942-4b2e1080-1dce-11ea-83a5-5c7f6a2d81d5.png)

**Description**  
![image](https://user-images.githubusercontent.com/50728113/70799306-474ebe00-1dcf-11ea-9dbb-9c2a9a9474f4.png)

We are facing guzzle library error 

**How to reproduce**  

**Possible Solution**  

**Additional context**

**Comment by alexeyshockov** [comment] 2019-12-13 12:21
A duplicate of #2448 

Please follow #2454 for a possible fix

**Comment by nimeshdixit** [comment] 2019-12-13 12:35
@alexeyshockov 

Thanks buddy #2454 is working for me.

**Closed** 2019-12-13 12:35 UTC
