### ISSUE TITLE
Missing tests folder in 6.2.1 distribution zip

### ISSUE THREAD

**Issue by snebes** [guzzle/guzzle#1535] opened 2016-07-20 14:03 UTC
I was looking to use the GuzzleHttp\Tests\Server to do some mock testing, but found all files in the test folder of the 6.2.1 (possibly earlier) were not included.  Is this intended, or are we expected to use @dev releases to run tests?

**Comment by Tobion** [comment] 2016-07-23 15:58
This is because of `.gitattributes` file. But since http://guzzle.readthedocs.io/en/latest/testing.html#test-web-server recommends to use the test server, it should not be in the `GuzzleHttp\Tests\` namespace but moved outside the tests folder, e.g. to `GuzzleHttp\Test\` for example. This is also how symfony does it for classes meant for testing by others.

**Comment by Tobion** [comment] 2016-07-23 15:59
Also this is a duplicate of #1533

**Comment by GrahamCampbell** [comment] 2016-07-23 16:27
No-bug. You should not be using anything not in src.

**Comment by GrahamCampbell** [comment] 2016-07-23 16:28
If people want to use that class, it needs moving out of the test suite.

**Comment by snebes** [comment] 2016-07-25 13:52
Documentation should be updated to reflect this.  The GuzzleHttp\Tests\Server class is used at http://docs.guzzlephp.org/en/latest/testing.html

**Comment by aejnsn** [comment] 2016-10-03 18:20
@snebes I brought this up a little while ago. Check this out: https://github.com/guzzle/guzzle/issues/1558

**Comment by sagikazarmark** [comment] 2016-11-08 12:42
A possible solution would be to add `--prefer-source` switch when developing locally.

But I agree with @GrahamCampbell if it's supposed to be used as a test toolkit, it needs to be moved out of tests (to another directory or a separate package so that it can be installed in dev environments only).

**Comment by sagikazarmark** [comment] 2016-12-22 23:06
Okay, after thinking about this and checking the documentation I have the following thoughts:

The documentation clearly states that there is no promise for the availability of the test toolkit. Also, using the `--prefer-source` option of composer the issue can be solved.

Furthermore (as I already said above) I agree with the others: IF (!) we want to provide a test toolkit, we should probably do that in a separate package. It might make sense to rewrite the current implementation in Go, that would remove the NodeJS dependency.

All in all: this issue can be solved by developer effort, so I am closing it in favor of #1699.

**Closed by sagikazarmark** 2016-12-22 23:06 UTC
Labels: Feature request
