### ISSUE TITLE
LogicException: The promise is already rejected

### ISSUE THREAD

**Issue by iliayatsenko** [guzzle/guzzle#3256] opened 2024-10-02 19:30 UTC
**Guzzle version(s) affected**: 7.*
**PHP version**: 8.3
**cURL version**: 8.10.1

**Description**  
Error **"LogicException: The promise is already rejected"** randomly happens when running lots of unsuccessful concurrent requests.

**How to reproduce**  
See small application to reproduce: https://github.com/iliayatsenko/guzzle-bug-report

**Possible Solution**  
Looks like aggregate promise is rejected more than once.

**Comment by GrahamCampbell** [comment] 2024-10-16 14:37
I think this is happening because a request has failed already before we're done adding more from the queue.

**Comment by GrahamCampbell** [comment] 2024-10-16 16:35
Does https://github.com/guzzle/promises/pull/173 fix your issue? It fixed it in my testing of your reproducer.

**Comment by GrahamCampbell** [comment] 2024-10-17 10:07
This has been resolved in promises release 2.0.4.

**Closed as completed by GrahamCampbell** 2024-10-17 10:07 UTC

**Comment by iliayatsenko** [comment] 2024-10-18 18:29
> Does [guzzle/promises#173](https://github.com/guzzle/promises/pull/173) fix your issue? It fixed it in my testing of your reproducer.

I only have this reproducer now, so if you tested with it and issue is gone, it's all right :)
Thank you very much!
