### ISSUE TITLE
HTTP Request headers are not present when using middleware

### ISSUE THREAD

**Issue by SubrataM3** [guzzle/guzzle#2119] opened 2018-08-05 13:56 UTC
| Q            | A
| ------------ | ---
| Bug?         | maybe
| New Feature? | no
| Version      | 6.3.3 (composer installed)

#### Actual Behavior
HTTP request headers (injected by middleware) are not present at the output of $e->getRequest() after an exception.

> __Invoke() method of the middleware  https://pastebin.com/3hHX20PG

But I can get headers if injected directly . 

```
$stack = HandlerStack::create();
$stack->push(Middleware::mapRequest(function (RequestInterface $request) {
	$request = $request->withHeader("header1","v1");
        $request = $request->withHeader("header2","v2");
        $request = $request->withHeader("header3","v3");
    return $request;
}));
```
I am sure that those custom headers are getting sent on each request. its just they are not visible if i do string output with Psr7\str($e->getRequest());
This is only happening for POST/PUT request but not for GET request.

#### Expected Behavior

HTTP request headers should be present in the output of $e->getRequest()

#### Steps to Reproduce

Code examples above.

**Comment by gmponos** [comment] 2019-12-29 16:44
This works for me:

```
$stack = HandlerStack::create();
$stack->push(Middleware::mapRequest(function (RequestInterface $request) {
    $request = $request->withHeader("Authorization", "v1");
    $request = $request->withHeader("header2", "v2");
    $request = $request->withHeader("header3", "v3");
    return $request;
}));

$client = new Client([
    'handler' => $stack
]);

try {
    $response = $client->request('post', 'https://www.nonexisting.com', [\GuzzleHttp\RequestOptions::CONNECT_TIMEOUT => 0.1]);
} catch (RequestException $e) {
    var_dump($e->getRequest()->getHeaders());
    die;
}
```

outputs:

```
php index.php 
array(5) {
  ["User-Agent"]=>
  array(1) {
    [0]=>
    string(39) "GuzzleHttp/6.3.3 curl/7.65.3 PHP/7.3.12"
  }
  ["Host"]=>
  array(1) {
    [0]=>
    string(19) "www.nonexisting.com"
  }
  ["Authorization"]=>
  array(1) {
    [0]=>
    string(2) "v1"
  }
  ["header2"]=>
  array(1) {
    [0]=>
    string(2) "v2"
  }
  ["header3"]=>
  array(1) {
    [0]=>
    string(2) "v3"
  }
}
```

Can you provide a better example reproducer?

**Comment by gmponos** [comment] 2020-05-18 20:19
Closing as no feedback was given.. feel free to submit your feedback and we can reopen this.

**Closed by gmponos** 2020-05-18 20:19 UTC
