### ISSUE TITLE
cURL error 0: The cURL request was retried 3 times and did not succeed

### ISSUE THREAD

**Issue by Verhaeg** [guzzle/guzzle#1723] opened 2017-01-13 18:43 UTC
Hi.. sorry to open this kind of issue again but contrary to the other issues we are having this problem in some specific circunstances.

We have a load balancer with 2 instances and they call another machine to fetch some data. This call is done using Guzzle and for some reason it started returning this exception but only for one of the instances the other still works fine.

Another point is that when the call to Guzzle is done through PHP CLI it does not throw the exception, only when the request comes from Apache.

The server is a Debian 8 with PHP 5.6

Code:
`try {
    $client   = new GuzzleHttp\Client(['base_uri' => 'http://my.server.com');
    $client->request('GET', '/some-url');
    echo "OK";
} catch (Exception $e) {
    echo $e->getMessage();
}`

When calling like `php script.php` it works! But when calling like `curl localhost/script.php` it throws the cURL error above.. And it only happens in one of the instances of the backend, not the other!

PS: This also affects other services that uses Guzzle to communicate.. doing the same request with curl works just fine

Thanks!

**Comment by sagikazarmark** [comment] 2017-01-13 20:55
Hi there,

Although you described perfectly what happens, sadly there is not much we can do with this information. 

Is there any further stack trace?
Does the apache log contain something?
What version of cURL do you use?
Are the two environments the same?
Are you sure that it's the PHP script that causes the issue and not the cURL call that you do to localhost?

Answering these questions might help solving the problem.
What if you try it with another HTTP client?

**Comment by Verhaeg** [comment] 2017-01-16 10:30
Hi sorry for the delay... let's see what I can add from what was requested:

This is the stacktrace:
```
#0 /project_folder/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(488): GuzzleHttp\Handler\CurlFactory::createRejection(Object(GuzzleHttp\Handler\EasyHandle), Array)
#1 /project_folder/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(147): GuzzleHttp\Handler\CurlFactory::retryFailedRewind(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Array)
#2 /project_folder/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(103): GuzzleHttp\Handler\CurlFactory::finishError(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory))
#3 /project_folder/vendor/guzzlehttp/guzzle/src/Handler/CurlHandler.php(43): GuzzleHttp\Handler\CurlFactory::finish(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory))
#4 /project_folder/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(493): GuzzleHttp\Handler\CurlHandler->__invoke(Object(GuzzleHttp\Psr7\Request), Array)
#5 /project_folder/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(147): GuzzleHttp\Handler\CurlFactory::retryFailedRewind(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Array)
#6 /project_folder/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(103): GuzzleHttp\Handler\CurlFactory::finishError(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory))
#7 /project_folder/vendor/guzzlehttp/guzzle/src/Handler/CurlHandler.php(43): GuzzleHttp\Handler\CurlFactory::finish(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory))
#8 /project_folder/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(493): GuzzleHttp\Handler\CurlHandler->__invoke(Object(GuzzleHttp\Psr7\Request), Array)
#9 /project_folder/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(147): GuzzleHttp\Handler\CurlFactory::retryFailedRewind(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Array)
#10 /project_folder/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(103): GuzzleHttp\Handler\CurlFactory::finishError(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory))
#11 /project_folder/vendor/guzzlehttp/guzzle/src/Handler/CurlHandler.php(43): GuzzleHttp\Handler\CurlFactory::finish(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory))
#12 /project_folder/vendor/guzzlehttp/guzzle/src/Handler/Proxy.php(28): GuzzleHttp\Handler\CurlHandler->__invoke(Object(GuzzleHttp\Psr7\Request), Array)
#13 /project_folder/vendor/guzzlehttp/guzzle/src/Handler/Proxy.php(51): GuzzleHttp\Handler\Proxy::GuzzleHttp\Handler\{closure}(Object(GuzzleHttp\Psr7\Request), Array)
#14 /project_folder/vendor/guzzlehttp/guzzle/src/PrepareBodyMiddleware.php(42): GuzzleHttp\Handler\Proxy::GuzzleHttp\Handler\{closure}(Object(GuzzleHttp\Psr7\Request), Array)
#15 /project_folder/vendor/guzzlehttp/guzzle/src/Middleware.php(30): GuzzleHttp\PrepareBodyMiddleware->__invoke(Object(GuzzleHttp\Psr7\Request), Array)
#16 /project_folder/vendor/guzzlehttp/guzzle/src/RedirectMiddleware.php(68): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Request), Array)
#17 /project_folder/vendor/guzzlehttp/guzzle/src/Middleware.php(59): GuzzleHttp\RedirectMiddleware->__invoke(Object(GuzzleHttp\Psr7\Request), Array)
#18 /project_folder/vendor/guzzlehttp/guzzle/src/HandlerStack.php(67): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Request), Array)
#19 /project_folder/vendor/guzzlehttp/guzzle/src/Client.php(275): GuzzleHttp\HandlerStack->__invoke(Object(GuzzleHttp\Psr7\Request), Array)
#20 /project_folder/vendor/guzzlehttp/guzzle/src/Client.php(123): GuzzleHttp\Client->transfer(Object(GuzzleHttp\Psr7\Request), Array)
#21 /project_folder/vendor/guzzlehttp/guzzle/src/Client.php(129): GuzzleHttp\Client->requestAsync('GET', '/TEST_URL', Array)
#22 /project_folder/public/health.php(63): GuzzleHttp\Client->request('GET', '/TEST_URL', Array)
#23 {main}
```

> Does the apache log contain something?
Nothing from Apache logs... 

> What version of cURL do you use?
cURL version: curl 7.38.0 (x86_64-pc-linux-gnu) libcurl/7.38.0 OpenSSL/1.0.1t zlib/1.2.8 libidn/1.29 libssh2/1.4.3 librtmp/2.3

> Are the two environments the same?
Both environments are exactly the same!

> Are you sure that it's the PHP script that causes the issue and not the cURL call that you do to localhost?
It is the PHP script because I got the same error when trying to access the URL from my browser!


As an extra note... I tried restarting the Apache server and aparently the issue resolved.. so it might be something with PHP Cache (using Zend OPCache)... but the fact that both instances are the same and only one  got this error and without any change on the instance or what it does...that is what is bugging me.. 
Does Guzzle cache anything else? Temp files or something?

Unfortunately I don't know a way to trigger this error on an environment... =/

If you have any ideas I'll appreciate any help on that!

**Comment by sagikazarmark** [comment] 2017-05-04 00:04
Guzzle does not cache anything. Since the error is not reproducible, I don't know what we can do. Have you tried provisioning a completely new host and trying to reproduce there?

**Comment by fingertips-solutions** [comment] 2019-01-09 20:47
I am having same issue.. when trying to connect with xmpp ejabberd server. i am getting this on xampp localhost as well as on linux based server... here is full error message. 

cURL error 0: The cURL request was retried 3 times and did not succeed. The most likely reason for the failure is that cURL was unable to rewind the body of the request and subsequent retries resulted in the same error. Turn on the debug option to see what went wrong. See https://bugs.php.net/bug.php?id=47204 for more information. (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)

**Comment by erlangp** [comment] 2019-07-07 12:10
i got same error. i just tried restart my apache server. error gone. :)

**Comment by MightyPork** [comment] 2019-11-06 15:45
Same error here, and after debugging with Wireshark, I see it's the remote server's fault - it returned the body but did not send headers (200 OK etc). This is not a guzzle error.

**Comment by okadwin** [comment] 2020-05-28 09:38
> i got same error. i just tried restart my apache server. error gone. :)

Me too, but I'm not as lucky as you. I spent the whole afternoon to solve this error.  Finally, I saw this...

**Comment by gmponos** [comment] 2020-05-28 09:49
Hi thank you @okadwin for also confirming that this is most probably an apache issue.

Since there is no more feedback from author if he tried the solutions mentioned and there are ppl confirming that the issue comes from the webserver I will close the issue.

**Closed by gmponos** 2020-05-28 09:49 UTC
Labels: kind/question

**Comment by brunoluan7** [comment] 2023-06-06 13:12
In my particular case, the problem was related to the misconfiguration of `sys_temp_dir` inside of my `php.ini` file.
After changing this configuration to a valid directory, the problem was gone ✔️ 

The following issue might help as well: https://github.com/guzzle/guzzle/issues/1363.

**Comment by Invidia19** [comment] 2025-10-13 08:30
i was deploying my app on flyio and this error happens after some time for no reason. 
so i recreate the machine, and it's working, thanks to this thread.
not a guzzleerror or code error
