### ISSUE TITLE
Provide alternatives to getConfig()

### ISSUE THREAD

**Issue by alexislefebvre** [guzzle/guzzle#3114] opened 2023-04-06 11:26 UTC
**Description**
In #2516, `getConfig()` was deprecated, but no replacement was suggested.

**Example**

We use https://packagist.org/packages/eightpoints/guzzle-bundle to use Guzzle in a Symfony project, with this config:

```yaml
# config/packages/eight_points_guzzle.yaml
eight_points_guzzle:
    clients:
        example_api:
            base_url: "https://api.example.com/"
            options:
                timeout: 30
                http_errors: true
                headers:
                    User-Agent: "EightPointsGuzzleBundle/v7"
                    Content-Type: 'application/json'
                    TokenID: '%example_api_key%'
            plugin: null
```

The method that use Guzzle can return `null` early if no key is provided for this client, so that we can enable or disable the calls to the external API by changing the value of `%example_api_key%` in our different environments.

```php
# src/ExampleClient.php

class ExampleClient
{
    public function __construct(
        private readonly \GuzzleHttp\Client $client,
    ) {
    }

    private function call(): ?array
    {
        if (!$this->client->getConfig()['headers']['TokenID']) {
            return null;
        }
        
        // …

        // the call to Guzzle is done here
        return json_decode(
            $this->client->post($uri, $parameters)->getBody(),
            true, 512, JSON_THROW_ON_ERROR
        );
    }
}
```

If `getConfig()` is removed in Guzzle 8, we won't be able to access to the config and disable these calls.

We could pass `%example_api_key%` to do the same thing but I think that it would be nice to rely only on the `$client` that already contain this value.

**Additional context**

Idea: add `getHeaders()` or something like `getHeader('TokenID')`, etc. to allow to access to the values that are accessible through `getConfig()` today with Guzzle 7.

See also #2514

**Comment by vaidas-lungis** [comment] 2023-06-28 16:59
use Middleware and check if request headers has TokenId ?

**Comment by alexislefebvre** [comment] 2023-06-28 18:05
> use Middleware and check if request headers has TokenId ?

Thanks, it looks interesting: https://docs.guzzlephp.org/en/stable/handlers-and-middleware.html#middleware

**Comment by GrahamCampbell** [comment] 2023-07-08 12:38
This is marked as deprecated, but probably I won't actually ever remove this. I just want to encourage people to not use it.

**Comment by srdjanpejic** [comment] 2023-09-26 09:30
I'm also using this Symfony package, like mentioned in the issue's description, and now I'm not sure how to push middleware to the existing client, currently I'm doing it like this:

```
$oauth = new OAuth2Middleware();
$this->guzzleClient->getConfig('handler')->push($oauth);
```

With `getConfig` being deprecated is there an alternative to achieve the same functionality?

**Comment by nimafallahian** [comment] 2023-10-19 11:36
I see you've mentioned you'll probably never remove this but the issue is I'm using phpstan to draw the attention to problematic lines of code in my codebase. I can ignore these lines but would prefer to have them out of deprecation notice or have an alternative to it. It would be wonderful if it's part of your plan to do one of these. :)

**Comment by GrahamCampbell** [comment] 2023-10-19 12:06
You can view this as technical debt in your code. We do not recommend using that function, but we appreciate many people do.

**Comment by alexislefebvre** [comment] 2023-10-19 13:07
> I'm also using this Symfony package, like mentioned in the issue's description, and now I'm not sure how to push middleware to the existing client, currently I'm doing it like this:
> 
> ```
> $oauth = new OAuth2Middleware();
> $this->guzzleClient->getConfig('handler')->push($oauth);
> ```
> 
> With `getConfig` being deprecated is there an alternative to achieve the same functionality?

Should it be asked and/or documented on the bundle repo? https://github.com/8p/EightPointsGuzzleBundle

**Comment by GrahamCampbell** [comment] 2023-10-19 13:18
You would need to create the handler then construct a guzzle client with said handler.

**Comment by GrahamCampbell** [comment] 2023-10-19 13:19
Much like in https://github.com/guzzle/guzzle/issues/3185.

**Comment by lkmorlan** [comment] 2024-01-04 18:22
In Drupal, a Guzzle client can be injected. We need to know what its settings are so that we can create a client with our own settings based on that. I don't see a way around this. This is what we use `getConfig()` for.

**Comment by LeoWie93** [comment] 2024-01-09 09:42
@GrahamCampbell 

> This is marked as deprecated, but probably I won't actually ever remove this. I just want to encourage people to not use it.

What speaks against marking this function as ` internal` insetad of `depcrecated`?

**Comment by Gonzalo1987** [comment] 2024-10-16 14:08
I believe the workaround to simply get the base uri when the DIP is used is very complex. I don't know if it's possible to retrieve this guzzle private properties otherwise. 

Talking about technical debt, probably create a handler stack and a middleware like the history and inject it using a decorator for use the DIP is probably not the best way for get a property that the $client object could directly expose.

**Comment by GrahamCampbell** [comment] 2024-10-16 14:21
> What speaks against marking this function as  internal insetad of depcrecated?

Internal means that it's only used internally, but actually nothing internally ever calls that function. I feel that deprecated is the correct way to indicate that we don't recommend this, but appreciate some people don't think in a compositional way and have code that needs this. I'm going to take no further action here.

**Closed by GrahamCampbell** 2024-10-16 14:21 UTC
