### ISSUE TITLE
Can`t change proxy

### ISSUE THREAD

**Issue by Cosmologist** [guzzle/guzzle#978] opened 2015-02-12 17:07 UTC
Hi guys!

Guzzle/CuRL don`t change proxy - i make 2 requests:
```php
$client->get('http://google.com', ['proxy' => 'socks5://95.183.8.141:11111']);
$client->get('http://google.com', ['proxy' => 'socks5://5.9.87.110:10093']);
```
I change GuzzleHttp\Ring\Client\CurlHandler::__invoke to dump curl options:
replace
```php
curl_exec($h);
```
on
```php
curl_setopt($h, CURLOPT_HEADER, 1);
curl_setopt($h, CURLINFO_HEADER_OUT, true);

curl_exec($h);

print_r(curl_getinfo($h));
```
Dump after first request:
```
Array
(
    [url] => http://google.com
    [content_type] => text/html; charset=UTF-8
    [http_code] => 302
    [header_size] => 266
    [request_size] => 96
    [filetime] => -1
    [ssl_verify_result] => 0
    [redirect_count] => 0
    [total_time] => 0.019186
    [namelookup_time] => 2.8E-5
    [connect_time] => 2.9E-5
    [pretransfer_time] => 9.0E-5
    [size_upload] => 0
    [size_download] => 258
    [speed_download] => 13447
    [speed_upload] => 0
    [download_content_length] => 258
    [upload_content_length] => 0
    [starttransfer_time] => 0.019104
    [redirect_time] => 0
    [redirect_url] => http://www.google.ru/?gfe_rd=cr&ei=09zcVKClBqaQ4gSI7YCwAw
    [primary_ip] => 95.183.8.141
    [certinfo] => Array
        (
        )

    [primary_port] => 11111
    [local_ip] => 188.120.229.69
    [local_port] => 55335
    [request_header] => GET / HTTP/1.1
Host: google.com
User-Agent: Guzzle/5.1.0 curl/7.26.0 PHP/5.5.21-1~dotdeb.1
)
```

Dump after second request:
```
Array
(
    [url] => http://www.google.ru/?gfe_rd=cr&ei=09zcVKClBqaQ4gSI7YCwAw
    [content_type] => text/html; charset=windows-1251
    [http_code] => 200
    [header_size] => 849
    [request_size] => 135
    [filetime] => -1
    [ssl_verify_result] => 0
    [redirect_count] => 0
    [total_time] => 0.060313
    [namelookup_time] => 2.1E-5
    [connect_time] => 2.2E-5
    [pretransfer_time] => 9.6E-5
    [size_upload] => 0
    [size_download] => 18263
    [speed_download] => 302803
    [speed_upload] => 0
    [download_content_length] => -1
    [upload_content_length] => 0
    [starttransfer_time] => 0.058606
    [redirect_time] => 0
    [redirect_url] =>
    [primary_ip] => 95.183.8.141
    [certinfo] => Array
        (
        )

    [primary_port] => 11111
    [local_ip] => 188.120.229.69
    [local_port] => 55336
    [request_header] => GET /?gfe_rd=cr&ei=09zcVKClBqaQ4gSI7YCwAw HTTP/1.1
Host: www.google.ru
User-Agent: Guzzle/5.1.0 curl/7.26.0 PHP/5.5.21-1~dotdeb.1
)
```

In the second query the proxy server is not changed. why?

**Comment by mtdowling** [comment] 2015-02-14 21:27
Instead of modifying it to dump out the curl_getinfo() data, can you dump the curl options that are being passed into curl to see if a different proxy is correctly passed to curl (it's the hash of options passed to curl_setopt_array)?

**Comment by mtdowling** [comment] 2015-04-25 18:49
I can't reproduce, so closing for now. Let me know if you come up with more information.

**Closed by mtdowling** 2015-04-25 18:49 UTC
