### ISSUE TITLE
Independent Request (Millisecond) Tracking

### ISSUE THREAD

**Issue by Erutan409** [guzzle/guzzle#1229] opened 2015-08-24 02:40 UTC
I'm curious if this already exists and I just can't seem to locate it in the latest library, but:

Is there the ability to retrieve the time taken (in milliseconds) to satisfy "a" guzzle request?  This would be akin to CURL_TOTAL_TIME information that's provided by the cURL php library.  If there isn't, can it be added?

**Comment by bmancone** [comment] 2015-08-24 13:39
I needed the same kind of feature so I wrote [this](https://github.com/bmancone/guzzle-stopwatch-middleware) 2 months ago. Basically, it adds a header (`X-Duration`) in the response with the time taken for the request in ms.

**Comment by mtdowling** [comment] 2015-09-01 23:04
Duplicate of https://github.com/guzzle/guzzle/issues/1152

**Closed by mtdowling** 2015-09-01 23:04 UTC
