### ISSUE TITLE
Post array params

### ISSUE THREAD

**Issue by peacook** [guzzle/guzzle#1338] opened 2015-12-16 02:55 UTC
I have problem when I try to post an array parameters.
Example, my data when I created at HTML form like this:
```HTML
<form method="POST">
<input name="field[]" value="field1" />
<input name="field[]" value="field2"/>
<input name="other" value="other_field"/>
<button>Submit<button>
</form>
```
So my correct data is: `field[]=field1&field[]=field2&other=other_field`

But in Guzzle (using `http_build_query` function), the data will be:
`field[**0**]=field1&field[**1**]=field2&other=other_field

I read PHP Function manual, a contributor [suggested](http://php.net/manual/en/function.http-build-query.php) fix this problem by follow code:
```PHP
$query = http_build_query($query);
$query = preg_replace('/%5B[0-9]+%5D/simU', '%5B%5D', $query);
```

**Comment by mtdowling** [comment] 2016-01-11 20:29
For now you need to build this array yourself manually. It's possible some kind of helper functionality will be added back into Guzzle, but nothing has been decided.

Closing a duplicate of https://github.com/guzzle/guzzle/issues/1196

**Closed by mtdowling** 2016-01-11 20:29 UTC
