### ISSUE TITLE
INTL_IDNA_VARIANT_2003 is deprecated

### ISSUE THREAD

**Issue by n3omaster** [guzzle/guzzle#2620] opened 2020-04-20 03:34 UTC
**Guzzle version(s) affected**: 6.5.3
**PHP version**: 7.3.16 (hint: `php --version`)
**cURL version**: 7.69.1 (hint: `php -i | grep cURL`)

**Description**  
My Telegram Bot is giving me this error when upgrade from 6.4.0 to 6.5.3:

idn_to_ascii(): INTL_IDNA_VARIANT_2003 is deprecated
--
in Utils.php line 35
at HandleExceptions->handleError(8192, 'idn_to_ascii(): INTL_IDNA_VARIANT_2003 is deprecated', '/home/erich33/vendor/guzzlehttp/guzzle/src/Utils.php', 35, array('uri' => object(Uri), 'options' => 0, 'idnaVariant' => 0))

**How to reproduce**  
When somebody message to my Telegram Bot, I have a script which send to my email the Exceptions, and turns now a hell with this error.

**Possible Solution**  
Downgrade to 6.4?
Something with symfony idn?

**Additional context**  
My actual composer.lock:

{
    "name": "laravel/laravel",
    "type": "project",
    "description": "The Laravel Framework.",
    "keywords": [
        "framework",
        "laravel"
    ],
    "license": "MIT",
    "require": {
        "php": "^7.3",
        "artesaos/seotools": "^0.17.1",
        "binarytorch/larecipe": "^2.2",
        "biscolab/laravel-recaptcha": "^4.0",
        "facebook/graph-sdk": "^5.7",
        "fideloper/proxy": "^4.0",
        "guzzlehttp/guzzle": "^6.5",
        "intervention/image": "^2.5",
        "irazasyed/telegram-bot-sdk": "3.1.0",
        "laravel-notification-channels/facebook": "^0.1.0",
        "laravel-notification-channels/facebook-poster": "^2.0",
        "laravel-notification-channels/telegram": "^0.3.0",
        "laravel-notification-channels/twitter": "^3.0",
        "laravel/framework": "^6.2",
        "laravel/passport": "^8.4",
        "laravel/socialite": "^4.1",
        "laravel/tinker": "^2.2",
        "overtrue/laravel-like": "^2.0",
        "predis/predis": "^1.1",
        "renatomarinho/laravel-page-speed": "^1.8",
        "rennokki/befriended": "^3.0",
        "rennokki/rating": "^2.0",
        "spatie/laravel-permission": "^3.11",
        "spatie/laravel-responsecache": "^6.3",
        "spatie/laravel-sitemap": "^5.3",
        "spatie/schema-org": "^2.2",
        "tedivm/fetch": "^0.7.1"
    },
    "require-dev": {
        "barryvdh/laravel-debugbar": "^3.2",
        "beyondcode/laravel-dump-server": "^1.0",
        "filp/whoops": "^2.0",
        "fzaninotto/faker": "^1.4",
        "mockery/mockery": "^1.0",
        "nunomaduro/collision": "^3.0",
        "phpunit/phpunit": "^9.0"
    },
    "config": {
        "optimize-autoloader": true,
        "preferred-install": "dist",
        "sort-packages": true
    },
    "extra": {
        "laravel": {
            "dont-discover": []
        }
    },
    "autoload": {
        "files": [
            "app/Helpers/Helper.php"
        ],
        "psr-4": {
            "App\\": "app/"
        },
        "classmap": [
            "database/seeds",
            "database/factories"
        ]
    },
    "autoload-dev": {
        "psr-4": {
            "Tests\\": "tests/"
        }
    },
    "minimum-stability": "dev",
    "prefer-stable": true,
    "scripts": {
        "post-autoload-dump": [
            "Illuminate\\Foundation\\ComposerScripts::postAutoloadDump",
            "@php artisan package:discover --ansi",
            "@php artisan optimize",
            "@php artisan view:clear",
            "@php artisan cache:clear",
            "@php artisan responsecache:clear"
        ],
        "post-root-package-install": [
            "@php -r \"file_exists('.env') || copy('.env.example', '.env');\""
        ],
        "post-create-project-cmd": [
            "@php artisan key:generate --ansi"
        ]
    }
}

**Comment by GrahamCampbell** [comment] 2020-04-20 08:42
I guess this is happening on this line: https://github.com/guzzle/guzzle/blob/6.5/src/Utils.php#L33.

**Comment by GrahamCampbell** [comment] 2020-04-20 08:43
That constant should be defined, however: https://github.com/symfony/polyfill-intl-idn/blob/master/bootstrap.php#L37.

**Comment by GrahamCampbell** [comment] 2020-04-20 08:44
What extensions do you have?

**Comment by GrahamCampbell** [comment] 2020-04-20 12:42
> My actual composer.lock:

**Comment by GrahamCampbell** [comment] 2020-04-20 12:42
> My actual composer.lock:

That is not your lock file.

**Comment by n3omaster** [comment] 2020-04-20 17:27
Hi GrahamCampell, I just did a PHP upgrade from 7.3 to 7.4, then do a composer update and everything worked fine. Thanks!

BTW: I suposse INTL_IDNA_VARIANT_UTS46 and INTL_IDNA_VARIANT_2003 are defined on other symfony package. Thanks!

**Comment by GrahamCampbell** [comment] 2020-04-20 18:40
Guzzle should also work on PHP 7.3, so we'd like to know what was going wrong.

**Comment by spaantje** [comment] 2020-04-22 08:04
Fyi; i'm (was) having the same issue 

Guzzle version(s) affected: 6.5.3
PHP version: 7.2.30 (hint: php --version)
cURL version: 7.19.7 (hint: php -i | grep cURL)

I downgraded to 6.5.2 to fix the issue.

**Comment by GrahamCampbell** [comment] 2020-04-22 12:36
Just to clarify, do you have the intl extension installed, or not?

**Comment by spaantje** [comment] 2020-04-22 13:48
@GrahamCampbell; intl is installed.

`extension_loaded('intl'); // -> true`

**Comment by spaantje** [comment] 2020-04-22 16:16
@GrahamCampbell i think it's caused by adding the symfony/polyfill-intl-idn package and/or removing your custom check (https://github.com/guzzle/guzzle/compare/6.5.2...6.5.3#diff-ff73e042e738204c6da009e2ed19f783L243)

My complete error was:
```php
production.ERROR: idn_to_ascii(): INTL_IDNA_VARIANT_2003 is deprecated {"exception":"[object] (ErrorException(code: 0): idn_to_ascii(): INTL_IDNA_VARIANT_2003 is deprecated at /httpdocs/vendor/guzzlehttp/guzzle/src/Utils.php:35)
```

Because the package is triggering the error:
https://github.com/symfony/polyfill-intl-idn/blob/master/Idn.php#L67

Hope this helps.

If i need to test anything, please let me know!

**Comment by GrahamCampbell** [comment] 2020-04-22 19:55
> Because the package is triggering the error:

Odd. That package code should never be run if the extension is loaded. Are you sure it is that line that's running, and not the same line in the C code?

**Comment by spaantje** [comment] 2020-04-23 07:07
Hmm, you right. 

The problem is; it was (and is) working fine when i use Guzzle version 6.5.2 but errors out on version 6.5.3 on: `/httpdocs/vendor/guzzlehttp/guzzle/src/Utils.php:35`

Maybe it's a server issue ? Do you have any idea ? 

When i run the following test script: 

```php
<?php

echo "<pre>";

echo "idn_to_ascii function_exists: "; var_dump(function_exists('idn_to_ascii'));
echo "<br><br>";

$idnaVariant = defined('INTL_IDNA_VARIANT_UTS46') ? INTL_IDNA_VARIANT_UTS46 : 0;
echo "idnaVariant: "; var_dump($idnaVariant);
echo "<br><br>";

echo "PHP_VERSION_ID: "; var_dump(PHP_VERSION_ID);
echo "<br><br>";

echo "idn_to_ascii test: "; var_dump(idn_to_ascii('google.com', 0));
echo "<br><br>";

echo "</pre>";
```

i get the following: 
```php
idn_to_ascii function_exists: bool(true)
idnaVariant: int(0)
PHP_VERSION_ID: int(70230)
idn_to_ascii test: string(10) "google.com"
```

(so then it does not throw a error)..

**Comment by GrahamCampbell** [comment] 2020-04-24 09:47
To confirm if the symfony code is being run can you add a var_dump or something before their code would have raised the deprecation warning?

**Comment by GrahamCampbell** [comment] 2020-04-24 10:10
Does https://github.com/guzzle/guzzle/pull/2626 fix your issue?

**Comment by ray-winkelman** [comment] 2020-04-25 06:59
Having this issue as well guys.

PHP 7.3
Guzzle 6.5.3

intl PHP extension's loaded.

Here's a stack trace because no one's posted one yet. This isn't a hard fix. I'll submit a pull if it wasn't 4am in Canada. 

```
[2020-04-25 06:51:18] production.ERROR: idn_to_ascii(): INTL_IDNA_VARIANT_2003 is deprecated {"exception":"[object] (ErrorException(code: 0): idn_to_ascii(): INTL_IDNA_VARIANT_2003 is deprecated at /home1/shadoxa8/public_html/production-gun-trader/source/vendor/guzzlehttp/guzzle/src/Utils.php:35)
[stacktrace]
#0 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(8192, 'idn_to_ascii():...', '/home1/shadoxa8...', 35, Array)
#1 /home1/shadoxa8/public_html/production-gun-trader/source/vendor/guzzlehttp/guzzle/src/Utils.php(35): idn_to_ascii('maps.googleapis...', 0)
#2 /home1/shadoxa8/public_html/production-gun-trader/source/vendor/guzzlehttp/guzzle/src/Client.php(220): GuzzleHttp\\Utils::idnUriConvert(Object(GuzzleHttp\\Psr7\\Uri), 0)
#3 /home1/shadoxa8/public_html/production-gun-trader/source/vendor/guzzlehttp/guzzle/src/Client.php(155): GuzzleHttp\\Client->buildUri(Object(GuzzleHttp\\Psr7\\Uri), Array)
#4 /home1/shadoxa8/public_html/production-gun-trader/source/vendor/guzzlehttp/guzzle/src/Client.php(183): GuzzleHttp\\Client->requestAsync('get', '/maps/api/geoco...', Array)
#5 /home1/shadoxa8/public_html/production-gun-trader/source/vendor/guzzlehttp/guzzle/src/Client.php(96): GuzzleHttp\\Client->request('get', '/maps/api/geoco...', Array)
#6 /home1/shadoxa8/public_html/production-gun-trader/source/app/Http/Controllers/PostController.php(408): GuzzleHttp\\Client->__call('get', Array)
```

**Comment by GrahamCampbell** [comment] 2020-04-25 07:51
>  I'll submit a pull if it wasn't 4am in Canada.

I have already prepared a PR, as I said. Please try it out and tell me if it fixes your issue.

**Comment by spaantje** [comment] 2020-04-25 14:45
> Does #2626 fix your issue?

I'm not that good with composer; how can i try this out ? (What do i need to require / put in my composer.json?)

**Comment by ray-winkelman** [comment] 2020-04-25 16:10
Ah, jeeze. I'm so sorry @GrahamCampbell. Chalk that up to being awake until 4am. 

This was a production issue, and I had to put the fire out pretty quickly. I ended up downgrading:

PHP 7.3 > 7.2
Guzzle 6.5.3 > 6.5.2

All at once, to fix the bug in the prod environment. I'm back online later. can we link you're PR to this issue? I'd love to get us back on the latest version(s) soon.

**Comment by GrahamCampbell** [comment] 2020-04-25 16:31
The PR is linked to the issue?

**Comment by spaantje** [comment] 2020-04-28 20:32
Sorry for the delay; @GrahamCampbell I can confirm that this fixes the issue on my end.
(had to setup a project to test this without destroying the production env)

**Comment by spaantje** [comment] 2020-04-30 08:27
Any idea when it will be merged in ? 😄

**Comment by GrahamCampbell** [comment] 2020-04-30 09:24
Not sure. It needs a review from the Guzzle core, and as much community feedback as possible.

**Comment by GrahamCampbell** [comment] 2020-04-30 09:24
We need to make absolutely sure that the next Guzzle 6.x release works properly, and doesn't break anything else.

**Comment by Dahdoul** [comment] 2020-04-30 13:16
> Ah, jeeze. I'm so sorry @GrahamCampbell. Chalk that up to being awake until 4am.
> 
> This was a production issue, and I had to put the fire out pretty quickly. I ended up downgrading:
> 
> PHP 7.3 > 7.2
> Guzzle 6.5.3 > 6.5.2
> 
> All at once, to fix the bug in the prod environment. I'm back online later. Can we link your PR to this issue? I'd love to get us back on the latest version(s) soon.

had to do the same, fixed the issue for now

**Comment by GrahamCampbell** [comment] 2020-04-30 13:39
@Dahdoul Please try with the patch. It is not useful to know that downgrading fixed it for you, because we have already established that there is a bug. What is only useful know is to know if the proposed fix actually fixes it for you.

**Comment by Dahdoul** [comment] 2020-04-30 14:34
> @Dahdoul Please try with the patch. It is not useful to know that downgrading fixed it for you, because we have already established that there is a bug. What is only useful know is to know if the proposed fix actually fixes it for you.

already applied the patch and it fixes the issue (PHP 7.3.17). I had to downgrade before just to fix the bug in production env.

**Comment by Drake24** [comment] 2020-05-04 13:36
```
local.ERROR: idn_to_ascii(): INTL_IDNA_VARIANT_2003 is deprecated {"exception":"[object] (ErrorException(code: 0): idn_to_ascii(): INTL_IDNA_VARIANT_2003 is deprecated at /home4/drake24/public_html/alpha.sushicode.com/vendor/guzzlehttp/guzzle/src/Utils.php:35)
[stacktrace]
#0 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(8192, 'idn_to_ascii():...', '/home4/drake24/...', 35, Array)
```

got the same error
"```
require": {
        "php": "^7.2",
        "clarification/sparkpost-laravel-driver": "^1.2",
        "fideloper/proxy": "^4.0",
        "guzzlehttp/guzzle": "^6.5.2",
        "jgrossi/corcel": "^3.1",
        "laravel/framework": "^6.2",
        "laravel/tinker": "^2.0",
        "vemcogroup/laravel-sparkpost-driver": "^3.0"
```

**Comment by Drake24** [comment] 2020-05-04 13:43
@GrahamCampbell sorry. I just applied manually the #2626 patch you made. and it worked

**Comment by amitshahc** [comment] 2020-05-04 15:44
I faced the same issue: on local windows pc php `7.2.30`, guzzle `6.5.3` working fine. but same versions on the server throws this above error with exact line numbers. downgrading guzzle `6.5.2` solved the issue onto the server. 
what I suspect is intl behaviour on both the side might be different. 

intl on local machine:
```
version | 1.1.0
-- | --
ICU version | 64.2
ICU Data version | 64.2
ICU TZData version | 2019a
ICU Unicode version | 12.1
```

intl on server:
```
version | 1.1.0
-- | --
ICU version | 4.2.1

```

**Comment by fredochieng** [comment] 2020-05-05 18:45
> That constant should be defined, however: https://github.com/symfony/polyfill-intl-idn/blob/master/bootstrap.php#L37.

Hello, I've been trying to fix this error too. What should I do this file?

**Comment by GrahamCampbell** [comment] 2020-05-05 19:18
Don't edit any of those files. Does #2626 fix your issue?

**Comment by fredochieng** [comment] 2020-05-05 19:23
@GrahamCampbell I'm kinda stuck applying #2626. Should I edit Utils.php file?

**Comment by fredochieng** [comment] 2020-05-05 19:34
In src/Utils.php I see some additions to the code, do I add these lines?

**Comment by runphp** [comment] 2020-05-12 15:09
Guzzle version(s) affected: 6.5.3
PHP version:7.3.13
cURL version:7.19.7
ICU version => 4.2.1
ICU TZData version => 2009j
ICU Unicode version => 5.1

update  "symfony/polyfill-intl-idn":"v1.16.0"

An error   _IDN conversion failed_  occurred

**Comment by runphp** [comment] 2020-05-12 15:15
This pull https://github.com/guzzle/guzzle/pull/2626 resolve error

**Comment by Nyholm** [comment] 2020-05-23 21:01
#2626 is merged.

**Closed by Nyholm** 2020-05-23 21:01 UTC
Labels: area/intl-icu

**Comment by flowser** [comment] 2020-05-25 08:52
i stll get ame error

**Comment by GrahamCampbell** [comment] 2020-05-25 08:54
@flowser Are you installing the latest dev version? The code has not actually been tagged yet.
