### ISSUE TITLE
disable_functions = curl_multi_exec and infinite loop until out of memory 

### ISSUE THREAD

**Issue by 4n70w4** [guzzle/guzzle#2114] opened 2018-07-28 12:53 UTC
| Q            | A
| ------------ | ---
| Bug?         | yes
guzzlehttp/guzzle | 6.3.3
guzzlehttp/promises | v1.3.1
guzzlehttp/psr7 | 1.4.2
php-http/guzzle6-adapter | v1.1.1

#### Actual Behavior

Infinite loop until out of memory

PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 20480 bytes)

...
PHP  19. GuzzleHttp\Handler\CurlMultiHandler->tick() /var/www/app/current/vendor/guzzlehttp/guzzle/src/Handler/CurlMultiHandler.php:125
...

#### Expected Behavior

throw exception

#### Steps to Reproduce

Configure php with:
disable_functions = curl_multi_exec

Use ClientInterface implementation
https://github.com/thephpleague/omnipay-common/blob/master/src/Common/Http/Client.php

```
$httpClient = new \Omnipay\Common\Http\Client();
$httpResponse = $httpClient->request('POST', 'https://google.com', [], '');
```

**Comment by gmponos** [comment] 2019-12-29 18:04
I am not sure what the expected behavior should be here, since you have the `curl_multi_exec`... No one can foresee what disabled functions someone might have.

I don't think this is an issue of guzzle... neither we should take action for every function that a developer might have disabled.. 

Instead since you want to have functions disabled you should manually initialize the Guzzle client with your own Handler. http://docs.guzzlephp.org/en/stable/handlers-and-middleware.html#handlers

Will leave this open for a while.. if some other maintainer has another point of view..

**Comment by gmponos** [comment] 2020-01-06 15:24
Closing. As mentioned I don't believe that the code should be alter for every possible function a developer might have disabled.

**Closed by gmponos** 2020-01-06 15:24 UTC
