### ISSUE TITLE
count(): Parameter must be an array or an object that implements Countable

### ISSUE THREAD

**Issue by philiplb** [guzzle/guzzle#1973] opened 2017-12-08 15:51 UTC
| Q            | A
| ------------ | ---
| Bug?         | yes
| New Feature? | no
| Version      | 6.2.1

#### Actual Behavior

I get an ErrorException/app/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php in handleError in this line:
```
if (count($this->handles) >= $this->maxHandles) {
```

#### Expected Behavior

There should not be an exception.

#### Possible Solutions

$this->handles should be an array or implement Countable. Maybe initialized with an empty array in the constructor.

**Comment by rawzone** [comment] 2017-12-09 13:11
Also seeing this problem.

Using Guzzle 6.2.1 in a Laravel project.

**Comment by Nyholm** [comment] 2017-12-10 09:13
Yes, This bug was fixed in 6.3. 

Thank you @rawzone for the help.

**Closed by Nyholm** 2017-12-10 09:13 UTC

**Comment by aequasi** [comment] 2018-02-01 10:27
Ahhh @Nyholm! You're everywhere :)

Thanks!

**Comment by Diego04** [comment] 2018-06-11 15:11
simple fix.

if (count($this->handles) >= $this->maxHandles)

if ( $this->handles != null && count($this->handles) >= $this->maxHandles )

**Comment by mfoote** [comment] 2018-08-31 13:02
FYI i am fairly certain this has to do with only php 7.2

**Comment by brazenvoid** [comment] 2018-09-11 04:26
@Diego04 Thank you! I can't thank you enough! 

I can't upgrade due to the whole erp built on user being gotten through the constructor __construct...

**Comment by Erutan409** [comment] 2018-12-14 21:54
@mfoote I'm seeing this on php 5.5.9.

**Comment by vinnoangel** [comment] 2019-01-04 12:31
The problem is in PHP 7.2 the parameter for count() can't be NULL. The warning gets displayed when $this->handles equals NULL. Just replace line 67 in CurlFactory.php with the following:

if (($this->handles ? count($this->handles) : 0) >= $this->maxHandles) {

**Comment by tamangtshering5** [comment] 2019-01-17 15:37
ErrorException in 51f0db6001c4f9b3b8a340919b69cacf9b5ea4aa.php line 227:
count(): Parameter must be an array or an object that implements Countable (View: C:\xampp\htdocs\bbtravels\resources\views\Frontend\Pages\index.blade.php)
@vinnoangel this error arises after i replaced line 67 with above line

**Comment by vinnoangel** [comment] 2019-01-18 02:30
Please produce line 227 for better understanding. Meanwhile I think the problem seems to be same with your former line 67. The count() parameter must be an array or object.
