### ISSUE TITLE
Introducing the library under PHP 7.3.x will cause the shell to return 1

### ISSUE THREAD

**Issue by qiqizjl** [guzzle/guzzle#2366] opened 2019-09-30 17:21 UTC
**Guzzle version(s) affected**: 6.3.3

**Description**  

Introducing the library under PHP 7.3.x will cause the shell to return 1
![image](https://user-images.githubusercontent.com/7540584/65900925-acf2f700-e3e9-11e9-8aaa-0044625d02c3.png)

but in php7.2.x is ok.
![image](https://user-images.githubusercontent.com/7540584/65901068-f9d6cd80-e3e9-11e9-9d58-9750e3417687.png)

**How to reproduce**  
~~~
 composer require guzzlehttp/guzzle 
~~~

test2.php:
~~~php
<?php
include "vendor/autoload.php";
~~~

composer.json
~~~json
{
    "require": {
        "guzzlehttp/guzzle": "^6.3"
    }
}

~~~

**Comment by Nyholm** [comment] 2019-10-18 17:17
I cannot reproduce. See this build on 7.3.9 where everything is fine: https://travis-ci.org/guzzle/guzzle/jobs/599645998

Im closing this for now. If you insist, please provide a Dockerfile of PHP 7.3 where you see this error.

**Closed by Nyholm** 2019-10-18 17:17 UTC
