### ISSUE TITLE
Redirect not working when there's no domain in 'Location' header

### ISSUE THREAD

**Issue by gytislakavicius** [guzzle/guzzle#1656] opened 2016-11-15 08:56 UTC
When a response contains 'Location' header which doesn't have a domain (e.g. '/not/working/properly.jpg'), Guzzle fails to build a correct Uri. Instead of using a domain from original request it throws an exception:
`Unable to parse URI: /not/working/properly.jpg`

On a quick look Psr7\Uri::resolve does some Uri merging if two UriInterface's are passed to it. So I think that if on \GuzzleHttp\RedirectMiddleware:213, UriInterface would be passed instead of naked 'Location' header string - it should work as supposed. Not 100% sure about that though.

**Comment by sagikazarmark** [comment] 2016-11-16 11:16
This is indeed strange, because we even have a test case for that: https://github.com/guzzle/psr7/blob/master/tests/UriResoverTest.php#L73

**Comment by haelbichalex** [comment] 2017-06-30 08:46
Did somebody find a fix for this?
my url should be `example.com/test.html` and I get `example.comtest.html`, when there is no full domain in Location header.

**Comment by Nokim** [comment] 2017-10-20 10:42
Did you tried to set 'base_uri' in client config?

**Comment by algorythm** [comment] 2019-04-09 11:22
Did you ever work on this? I have the exact same issue. When a website redirects to an absolute path, it fails.

Example: Let's say that a request to `http://example.com` returns a 301 to `/us/en`, then GuzzleHttp throws an exception with message:

> Redirect URI, /us/en, does not use one of the allowed redirect protocols: http, https

**Comment by mrimann** [comment] 2020-02-24 15:18
Just stumbled over the same issue:

```
➜  ~ curl -I http://www.somevaliddomain.tld
HTTP/1.1 302 Moved Temporarily
Date: Mon, 24 Feb 2020 15:13:57 GMT
Server: Apache
Connection: close
X-Powered-By: pimcore
Location: /de
X-Powered-By: PleskLin
Content-Type: text/html; charset=UTF-8
```

Calling that domain in the browser via "http://www.somevaliddomain.tld" results in being forwarded to "http://www.somevaliddomain.tld/de" - but Guzzle throws the following error at me:
```
Redirect URI, /de, does not use one of the allowed redirect protocols: http, https
```

My Guzzle-Client is not using a Base-URI, has the option `'allow_redirects' => true` set upon initialization - and the request is done against a domain.

Expected behaviour would be like in the Browser - Guzzle shall follow the `/de` redirection and interpret it as `somevaliddomain.tld/de` in this case.

**Comment by mrimann** [comment] 2020-10-05 11:00
Problem still happening.

**Comment by GrahamCampbell** [comment] 2020-10-05 11:56
We're open to PRs. ;)

**Comment by alex-moreno** [comment] 2020-12-31 10:41
this happens to me when you pass a uri that does not contain http or https, ie:

```google.com```

instead of 

```http://google.com```

**Comment by alex-moreno** [comment] 2020-12-31 11:01
not sure it's the right approach, but there it goes a PR. Any feedback welcome please.

**Comment by Nyholm** [comment] 2021-01-30 08:49
Note that the URL should be absolute or relative. 
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Location

Doing `google.com` is not valid. But `/index.html` is.

**Comment by GrahamCampbell** [comment] 2021-02-11 15:17
Closing as per the above discussion, and the associated PR.

**Closed** 2021-02-11 15:16 UTC
