### ISSUE TITLE
Authorization Bearer doesn't work

### ISSUE THREAD

**Issue by gfazioli** [guzzle/guzzle#1333] opened 2015-12-11 14:24 UTC
Hi there,

I try to get a request with Authorization bearer but it doesn't work. Have a look to my code:

```php
// in $this->endpoint I have https://172.17.8.111:443
$this->httpClient = new HttpClient( [ "base_uri" => $this->endpoint ] );

// prepare headers
$this->headers = [
      'verify'          => false,
      'allow_redirects' => true,
      'headers'         => [
        'Accept'        => 'application/json',
        'Authorization' => 'Bearer {$myToken}'
      ]
    ];

$this->response = $this->httpClient->get( '/api/', $this->headers );
```
 I got `[GuzzleHttp\Exception\ClientException] Client error: 401`

the same request made via curl (in shell or php code) works!

What I wrong?

**Comment by gfazioli** [comment] 2015-12-12 11:29
This is my debug option

```
* Hostname was NOT found in DNS cache
*   Trying 172.17.8.111...
* Connected to 172.17.8.111 (172.17.8.111) port 443 (#0)
* successfully set certificate verify locations:
*   CAfile: none
  CApath: /etc/ssl/certs
* SSL connection using ECDHE-RSA-AES256-SHA
* Server certificate:
*      subject: CN=kube-apiserver-172.17.8.111
*      start date: 2015-12-11 08:32:28 GMT
*      expire date: 2016-12-10 08:32:28 GMT
*      issuer: CN=kube-ca
*      SSL certificate verify result: unable to get local issuer certificate (20), continuing anyway.
> GET /api/ HTTP/1.1
User-Agent: GuzzleHttp/6.1.0 curl/7.35.0 PHP/5.5.9-1ubuntu4.14
Host: 172.17.8.111
Accept: application/json
Authorization: Bearer {mykey}

< HTTP/1.1 401 Unauthorized
< Content-Type: text/plain; charset=utf-8
< Date: Fri, 11 Dec 2015 18:17:47 GMT
< Content-Length: 13
< 
* Connection #0 to host 172.17.8.111 left intact
```

**Comment by mtdowling** [comment] 2015-12-12 18:13
Hm. This is suspicious:

> SSL certificate verify result: unable to get local issuer certificate (20), continuing anyway.

Can you show the verbose curl output when running from the command line?

**Comment by gfazioli** [comment] 2015-12-14 16:25
@mtdowling This is my curl from console

```
$ curl -vsSk -X "GET" "https://172.17.8.111:443/api/" -H "Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJkZWZhdWx0Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZWNyZXQubmFtZSI6ImRlZmF1bHQtdG9rZW4tZW83eHYiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoiZGVmYXVsdCIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50LnVpZCI6IjcwOWQxODg0LTlmZTItMTFlNS1iNmNkLTA4MDAyNzViZDBhNiIsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDpkZWZhdWx0OmRlZmF1bHQifQ.RonmnLC9BF08QKY_QQETNMgEz-aRTb60V2iPKx-cshBMtfYU0GqnN_c-jGtldk887AVO8tJqF5qXuUAGuy2UuXOTbmubNt06erQa_OqtkfB9s6uanl6F9b0njcAFx2LKaown1dpXarsqJSzPs8F9q6gbzCSWYydfmTB4lgOL6pG0cGfZaNnWhcCeXfXeZFJVTZ2oqT6vDGZPd-OuVGTkrKQQcBFE9xiYU7ElVCm-GwtBB6bd8paKO2DGmLBAt5-nJJeeB32COCMUHHn_InxBR27CLxET2cx1pkNBkJZSv1r5WwdlLeThiRk7GlyHP-coog_yAjnwyQFzxE8tgu18kg"
* Hostname was NOT found in DNS cache
*   Trying 172.17.8.111...
* Connected to 172.17.8.111 (172.17.8.111) port 443 (#0)
* successfully set certificate verify locations:
*   CAfile: none
  CApath: /etc/ssl/certs
* SSLv3, TLS handshake, Client hello (1):
* SSLv3, TLS handshake, Server hello (2):
* SSLv3, TLS handshake, CERT (11):
* SSLv3, TLS handshake, Server key exchange (12):
* SSLv3, TLS handshake, Request CERT (13):
* SSLv3, TLS handshake, Server finished (14):
* SSLv3, TLS handshake, CERT (11):
* SSLv3, TLS handshake, Client key exchange (16):
* SSLv3, TLS change cipher, Client hello (1):
* SSLv3, TLS handshake, Finished (20):
* SSLv3, TLS change cipher, Client hello (1):
* SSLv3, TLS handshake, Finished (20):
* SSL connection using ECDHE-RSA-AES256-SHA
* Server certificate:
* 	 subject: CN=kube-apiserver-172.17.8.111
* 	 start date: 2015-12-11 08:32:28 GMT
* 	 expire date: 2016-12-10 08:32:28 GMT
* 	 issuer: CN=kube-ca
* 	 SSL certificate verify result: unable to get local issuer certificate (20), continuing anyway.
> GET /api/ HTTP/1.1
> User-Agent: curl/7.35.0
> Host: 172.17.8.111
> Accept: */*
> Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJkZWZhdWx0Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZWNyZXQubmFtZSI6ImRlZmF1bHQtdG9rZW4tZW83eHYiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoiZGVmYXVsdCIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50LnVpZCI6IjcwOWQxODg0LTlmZTItMTFlNS1iNmNkLTA4MDAyNzViZDBhNiIsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDpkZWZhdWx0OmRlZmF1bHQifQ.RonmnLC9BF08QKY_QQETNMgEz-aRTb60V2iPKx-cshBMtfYU0GqnN_c-jGtldk887AVO8tJqF5qXuUAGuy2UuXOTbmubNt06erQa_OqtkfB9s6uanl6F9b0njcAFx2LKaown1dpXarsqJSzPs8F9q6gbzCSWYydfmTB4lgOL6pG0cGfZaNnWhcCeXfXeZFJVTZ2oqT6vDGZPd-OuVGTkrKQQcBFE9xiYU7ElVCm-GwtBB6bd8paKO2DGmLBAt5-nJJeeB32COCMUHHn_InxBR27CLxET2cx1pkNBkJZSv1r5WwdlLeThiRk7GlyHP-coog_yAjnwyQFzxE8tgu18kg
> 
< HTTP/1.1 200 OK
< Content-Type: application/json
< Date: Mon, 14 Dec 2015 16:23:08 GMT
< Content-Length: 32
< 
{
  "versions": [
    "v1"
  ]
* Connection #0 to host 172.17.8.111 left intact
```

**Comment by gfazioli** [comment] 2015-12-14 16:27
@mtdowling as you can see the curl works properly, but the same request with guzzle failed...

**Comment by mtdowling** [comment] 2015-12-14 23:50
Looks like the Accept header is different. Can you try sending "*/*" with Guzzle? What about removing the Guzzle user-agent as well?

**Comment by gfazioli** [comment] 2015-12-15 09:06
@mtdowling same result

![image](https://cloud.githubusercontent.com/assets/432181/11806445/844c18ba-a313-11e5-8d21-3287d75bc38d.png)

**Comment by gfazioli** [comment] 2015-12-15 09:10
@mtdowling `GET /`

![image](https://cloud.githubusercontent.com/assets/432181/11806539/16b5c0d4-a314-11e5-9919-a12a47a05edd.png)

**Comment by gfazioli** [comment] 2016-01-06 20:10
@mtdowling any news?

**Comment by mtdowling** [comment] 2016-01-06 20:30
It looks like Guzzle is sending the right request, so unfortunately, I'm not sure what the issue is. You said that you got this to work using PHP's curl. Can you show how you did that? Maybe the options you use there could be compared against the curl options used in Guzzle.

**Comment by gfazioli** [comment] 2016-01-11 10:08
@mtdowling Hi, sorry for the delay, so, with cURL I used a my trait... however the core code is:

```php
// set auth
    $this->headers = [
      "Authorization: Bearer " . env( 'KUBERNETES_SECRET' ),
    ];

    $ch = curl_init( $this->endpoint . $path );
    curl_setopt( $ch, CURLOPT_RETURNTRANSFER, true );
    curl_setopt( $ch, CURLOPT_FOLLOWLOCATION, true );

    curl_setopt( $ch, CURLOPT_SSL_VERIFYPEER, false );
    curl_setopt( $ch, CURLOPT_HTTPHEADER, $this->headers );

    $res              = curl_exec( $ch );
    $this->httpStatus = curl_getinfo( $ch, CURLINFO_HTTP_CODE );
    curl_close( $ch );
```
The code above works
I hope that this can help you

**Comment by mtdowling** [comment] 2016-03-05 02:27
I have no idea why this isn't working. The only thing I can think for you to try is comment out this line and see if it changes things (I highly doubt it will): https://github.com/guzzle/guzzle/blob/master/src/Handler/CurlFactory.php#L196.

I can't reproduce this, so I'll close this issue until more information can be provided to reproduce this issue.

**Closed by mtdowling** 2016-03-05 02:27 UTC

**Comment by gfazioli** [comment] 2016-03-05 11:30
@mtdowling ok, I'll try asap... thank you

**Comment by jpirkey** [comment] 2016-03-21 14:23
Not sure if it is just a typo here or not, but you are using single quotes on the `Authorization` header, so `Bearer {$myToken}` is what will actually be sent to the server ... as seen in your debug output:

```
Authorization: Bearer {mykey}
```

**instead of**

```
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJkZWZhdWx0Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZWNyZXQubmFtZSI6ImRlZmF1bHQtdG9rZW4tZW83eHYiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoiZGVmYXVsdCIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50LnVpZCI6IjcwOWQxODg0LTlmZTItMTFlNS1iNmNkLTA4MDAyNzViZDBhNiIsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDpkZWZhdWx0OmRlZmF1bHQifQ.RonmnLC9BF08QKY_QQETNMgEz-aRTb60V2iPKx-cshBMtfYU0GqnN_c-jGtldk887AVO8tJqF5qXuUAGuy2UuXOTbmubNt06erQa_OqtkfB9s6uanl6F9b0njcAFx2LKaown1dpXarsqJSzPs8F9q6gbzCSWYydfmTB4lgOL6pG0cGfZaNnWhcCeXfXeZFJVTZ2oqT6vDGZPd-OuVGTkrKQQcBFE9xiYU7ElVCm-GwtBB6bd8paKO2DGmLBAt5-nJJeeB32COCMUHHn_InxBR27CLxET2cx1pkNBkJZSv1r5WwdlLeThiRk7GlyHP-coog_yAjnwyQFzxE8tgu18kg
```

which is what your curl request is sending.  Simply changing it to double quotes, should get you what you want.

```php
// prepare headers
$this->headers = [
      'verify'          => false,
      'allow_redirects' => true,
      'headers'         => [
        'Accept'        => 'application/json',
        'Authorization' => "Bearer {$myToken}"
      ]
    ];
```

this way php parses the string and replaces `{$myToken}` with the actual token.

**Comment by boedy** [comment] 2016-07-06 08:47
If your still having this issue, it might be related to your token which isn't being parsed when using single quotes:

`'Authorization' => 'Bearer {$myToken}'`
should be
`'Authorization' => "Bearer {$myToken}"`

**Comment by gfazioli** [comment] 2016-07-06 09:22
@boedy yes, already fixed. Anyway, now it works... I don't know why :)

**Comment by btica-ro** [comment] 2017-07-25 15:46
$var = '1234';

echo "Value: $var"; //    Value: 1234
echo 'Value: $var'; //      Value: $var

**Comment by dunnleaddress** [comment] 2017-08-27 07:11
it helps me resolve same issue thanks @boedy - for the fix , and @gfazioli - for explaining it.

**Comment by dungleaddress** [comment] 2019-02-01 07:18
@gfazioli Can you please share how you fixed your code? @gfazioli Thanks!

**Comment by sadhikari0102** [comment] 2020-01-23 23:59
Can we reopen this. I think this issue persists when there is a redirect in place. When I am locally communicating between two services over local host using guzzle, everything runs fine, but if I deploy destination service on kubernetes, it returns 401, and the logs on the destination service suggests that 'Authorization' header was not received by it. Even the headers from the Response object in the exception suggest that there is no auth header, even though it is present in the Request object.
Here is the snapshot of request and response:
![image](https://user-images.githubusercontent.com/22922598/73034304-7adf2800-3e12-11ea-87b6-e2a4821937e9.png)

**Comment by cboulanger** [comment] 2020-02-24 20:34
Same problem here - using Codeception's PhpBrowser module which depends on Guzzle. The 'Authorization: Bearer' header is being passed around right until the `curl_exec` call - but it is not sent out.

![Bildschirmfoto 2020-02-24 um 21 32 55](https://user-images.githubusercontent.com/75390/75188880-4f22cb00-574d-11ea-9894-1979689cb075.png)

**Comment by yszty** [comment] 2021-01-16 14:21
I suspect that the problem lays in undefined port or protocol. Headers content wasn't an issue for me. I resolved same problem by changing:

`115.12.3.44`
to
`115.12.3.44:80`

also tested 

`115.12.3.44`
to
`http://115.12.3.44`

Translated by @ImChriz ;)))
