### ISSUE TITLE
Create a request with query having duplicate keys

### ISSUE THREAD

**Issue by gmponos** [guzzle/guzzle#1450] opened 2016-04-14 08:34 UTC
There are libraries in java that automatically translate the query from the following url into list objects.

    https://myurl.com/test?mykey=value1&mykey=value2

I was wondering if there could be something like that implemented in guzzle

    $client->get('myurl.com', [
        'query' => [
            'mykey' => [
                'value1'
                'value2'
            ]
        ]
    ]);

**Comment by gmponos** [comment] 2016-04-14 08:44
For example the following library

``jax-rs``
http://www.mkyong.com/webservices/jax-rs/jax-rs-queryparam-example/

**Comment by mtdowling** [comment] 2016-04-15 21:38
Thanks for the suggestion. I'm on the fence as to what level Guzzle should support something like this in Guzzle itself. It could easily be a separate library, and I haven't come up with a design I really like for this.This is a duplicate of https://github.com/guzzle/guzzle/issues/1196 so closing in favor of that long standing issue.

**Closed by mtdowling** 2016-04-15 21:38 UTC
