### ISSUE TITLE
Guzzle URL encoding is wrong

### ISSUE THREAD

**Issue by 13r** [guzzle/guzzle#2755] opened 2020-09-14 12:21 UTC
**Guzzle version(s) affected**: 7.0.1
**PHP version**: 7.4.8 
**cURL version**: 7.71.1

**Description**  
Guzzle URL encoding is wrong.

**How to reproduce**  
```
$client = new GuzzleHttp\Client(); 
$client->get('https://sapoconcho.org/wp-content/uploads/2019/03/0110-VEHICULO-DEL-EJÉRCITO.jpg');
```

**Possible Solution**  

**Additional context**  
Log:
```
PHP Fatal error:  Uncaught GuzzleHttp\Exception\ClientException: Client error: `GET https://sapoconcho.org/wp-content/uploads/2019/03/0110-VEHICULO-DEL-EJ%C3_RCITO.jpg` resulted in a `404 Not Found`
```

"É" should be encoded as "%C3%89" instead of "%C3_", or at least to have a way to avoid url encoding at all.

**Comment by mfn** [comment] 2020-09-14 12:24
Does the suggestion from https://github.com/guzzle/guzzle/issues/2734#issuecomment-661696158 maybe work here too?

**Comment by 13r** [comment] 2020-09-14 12:35
> Does the suggestion from [#2734 (comment)](https://github.com/guzzle/guzzle/issues/2734#issuecomment-661696158) maybe work here too?

Tried:
```
$uri = new GuzzleHttp\Psr7\Uri('https://sapoconcho.org/wp-content/uploads/2019/03/0110-VEHICULO-DEL-EJÉRCITO.jpg');
var_dump($uri->__toString());
```
And i get:
```
string(83) "https://sapoconcho.org/wp-content/uploads/2019/03/0110-VEHICULO-DEL-EJ%C3_RCITO.jpg"
```

Same problem :S.

**Comment by Nyholm** [comment] 2020-09-20 09:26
Guzzle is using Guzzle/psr7 for this. 

When Im running 

```php
$uri = new \GuzzleHttp\Psr7\Uri('https://sapoconcho.org/wp-content/uploads/2019/03/0110-VEHICULO-DEL-EJÉRCITO.jpg');
var_dump($uri->__toString());
```
then I get `string(85) "https://sapoconcho.org/wp-content/uploads/2019/03/0110-VEHICULO-DEL-EJ%C3%89RCITO.jpg"`

Guzzle/psr7 is just using `rawurlencode()`. See https://3v4l.org/XibgE

Im closing this as I cannot reproduce. Please open a PR with a failing test on guzzle/psr7 if you still think this is an issue.

**Closed by Nyholm** 2020-09-20 09:26 UTC
