### ISSUE TITLE
Include NodeJS server in normal package

### ISSUE THREAD

**Issue by Konafets** [guzzle/guzzle#1533] opened 2016-07-19 08:52 UTC
The documentation mention the usage of a NodeJS server to test "real" HTTP calls but the NodeJS server is not present when installing Guzzle via Composer because of the settings in .gitattributes.

**Comment by mtdowling** [comment] 2016-08-24 22:19
Duplicate of https://github.com/guzzle/guzzle/issues/1535

**Closed by mtdowling** 2016-08-24 22:19 UTC
