### ISSUE TITLE
PHP Guzzle (Google OAuth) - Sending 2 requests on same instance give 400 bad request

### ISSUE THREAD

**Issue by aditya43** [guzzle/guzzle#1958] opened 2017-11-22 12:22 UTC
I'm using Guzzle 6. When I send API (GET) request on the same instance on which I received authorization token (POST), I get a 400 bad request error.

Following is the code :

```
// Get Access Token Request (POST)
$response = $this->client->post($this->accessTokenUrl, [
            'form_params' =>
            [
                'code'          => $code,
                'client_id'     => $this->clientId,
                'client_secret' => $this->clientSecret,
                'redirect_uri'  => $this->callbackUrl,
                'grant_type'    => 'authorization_code'
            ]
        ], [
            'headers' => [
                'encoding' => 'application/x-www-form-urlencoded'
            ]
        ]);

$response = json_decode($response->getBody()); // Works fine, I do receive an access token.

/*+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+*/

// Api Call Request (GET)
// $client = new Client(); // Everything works fine if we create a new Client instance here and send below request on it,
$response = $this->client->request('GET', 'https://www.googleapis.com/plus/v1/people/me?access_token=' . $response->access_token, [
            'headers' =>
            [
                'Authorization' => 'Bearer ' . $response->access_token,
                'Host'          => 'www.googleapis.com'
            ]
        ]);

json_decode($response->getBody()); // Doesn't work. It gives 400 bad request if I don't new up the Client() instance above.
```

I suspect it has something to do with the headers. Kindly correct if I'm wrong.

**Comment by alexeyshockov** [comment] 2017-11-22 14:06
Try to use [`debug`](http://docs.guzzlephp.org/en/stable/request-options.html#debug) option to see the raw HTTP request (to find the difference). It would be much simpler to say the reason when we know the difference between requests in both cases.

**Comment by willmkt** [comment] 2017-12-11 03:57
@aditya43 did you find the solution? i got a similar problem and can't find a solution.

**Comment by aditya43** [comment] 2017-12-11 06:47
@willmkt , Nop I didn't find any solution. I just new up the Client instance and fire the request anyway. It seems to fix the issue.

**Comment by Tobion** [comment] 2020-02-16 02:53
Closing as there cannot be much done without a reproducer or debug information. Maybe you configured the original guzzle client with some default header that are not valid on the second request?

**Closed by Tobion** 2020-02-16 02:53 UTC
