### ISSUE TITLE
Cannot read from non-readable stream

### ISSUE THREAD

**Issue by slaanesh** [guzzle/guzzle#1784] opened 2017-03-21 16:10 UTC
`GuzzleHttp\Exception\RequestException::getResponseBodySummary` doesn't check properly the `$response` parameter: it checks if its seekable but forgets to check if it's readable hence throwing a RuntimeException when it's not

A typical trace of such an exception would be:
```
guzzlehttp/guzzle/src/Exception/RequestException.php (132)
guzzlehttp/guzzle/src/Exception/RequestException.php (105)
guzzlehttp/guzzle/src/Middleware.php (65)
guzzlehttp/promises/src/Promise.php (203)
guzzlehttp/promises/src/Promise.php (156)
guzzlehttp/promises/src/TaskQueue.php (47)
guzzlehttp/promises/src/Promise.php (246)
guzzlehttp/promises/src/Promise.php (223)
guzzlehttp/promises/src/Promise.php (267)
guzzlehttp/promises/src/Promise.php (225)
guzzlehttp/promises/src/Promise.php (62)
guzzlehttp/guzzle/src/Client.php (129)
```

**Comment by gmponos** [comment] 2018-12-18 15:59
The issue is fixed https://github.com/guzzle/guzzle/blob/master/src/Exception/RequestException.php#L129

but unfortunately not tagged (latest tag code: https://github.com/guzzle/guzzle/blob/6.3.3/src/Exception/RequestException.php#L129)

**Comment by MalyshevDmitry** [comment] 2018-12-18 16:11
@gmponos Sorry, I don't sure about it.

This code makes GET request for not found image:
```
$temporaryFilePath = PathHelper::getTemporaryFilePath();
$fileResource = fopen($temporaryFilePath, 'wb');

try {

    $this->httpClient->request('GET', $url, [
        'sink'        => $fileResource,
        'verify'      => false,
        'http_errors' => true
    ]);

    @fclose($fileResource);
    return $temporaryFilePath;

} catch (RequestException $e) {
    throw new RuntimeException('Impossible to download file');
} finally {
    @fclose($fileResource);
}
```

But there is an exception:
```
Cannot read from non-readable stream at #0 /vendor/guzzlehttp/guzzle/src/Exception/RequestException.php(139): GuzzleHttp\Psr7\Stream->read(120)
#1 /vendor/guzzlehttp/guzzle/src/Exception/RequestException.php(107): GuzzleHttp\Exception\RequestException::getResponseBodySummary(Object(GuzzleHttp\Psr7\Response))
#2 /vendor/guzzlehttp/guzzle/src/Middleware.php(66): GuzzleHttp\Exception\RequestException::create(Object(GuzzleHttp\Psr7\Request), Object(GuzzleHttp\Psr7\Response))
#3 /vendor/guzzlehttp/promises/src/Promise.php(203): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Response))
#4 /vendor/guzzlehttp/promises/src/Promise.php(156): GuzzleHttp\Promise\Promise::callHandler(1, Object(GuzzleHttp\Psr7\Response), Array)
#5 /vendor/guzzlehttp/promises/src/TaskQueue.php(47): GuzzleHttp\Promise\Promise::GuzzleHttp\Promise\{closure}()
#6 /vendor/guzzlehttp/promises/src/Promise.php(246): GuzzleHttp\Promise\TaskQueue->run(true)
#7 /vendor/guzzlehttp/promises/src/Promise.php(223): GuzzleHttp\Promise\Promise->invokeWaitFn()
#8 /vendor/guzzlehttp/promises/src/Promise.php(267): GuzzleHttp\Promise\Promise->waitIfPending()
#9 /vendor/guzzlehttp/promises/src/Promise.php(225): GuzzleHttp\Promise\Promise->invokeWaitList()
#10 /vendor/guzzlehttp/promises/src/Promise.php(62): GuzzleHttp\Promise\Promise->waitIfPending()
#11 /vendor/guzzlehttp/guzzle/src/Client.php(131): GuzzleHttp\Promise\Promise->wait()
#12 /src/App/HttpClient/HttpClient.php(30): GuzzleHttp\Client->request('GET', 'https://api.sel...', Array)
```

**Comment by slaanesh** [comment] 2019-03-12 11:20
@gmponos thanks for fixing it in the master branch, I've been expecting since then to have a valid production release I can deploy. Any idea when that will be possible?

**Comment by gmponos** [comment] 2019-03-12 11:51
Hello @slaanesh.. 

Sorry to say but I am not a mentainer of this project...
Secondly the credits shouldn't go to me... I dont think I was the one applying the fix.

**Comment by slaanesh** [comment] 2019-03-12 12:01
ha sorry. It seems I can't find a proper list of maintainers of this repo. Would that be you @jeremeamia or @mtdowling?

**Comment by gmponos** [comment] 2019-12-29 12:54
Closing as this is resolved now.

**Closed by gmponos** 2019-12-29 12:54 UTC
