### ISSUE TITLE
Custom header triggers error not valid header value

### ISSUE THREAD

**Issue by it-can** [guzzle/guzzle#2998] opened 2022-03-20 18:51 UTC
**Guzzle version(s) affected**: 7.4
**PHP version**: 8.1.4
**cURL version**: 7.82.0

**Description**  
I was testing this library (https://github.com/mollie/mollie-api-php/issues/612), which sets a custom header with ```php_uname()```. And my docker returns this value: ```Linux f0f489981e90 5.10.104-linuxkit #1 SMP Wed Mar 9 19:05:23 UTC 2022 x86_64```.  This will trigger an error

```
"Linux f0f489981e90 5.10.104-linuxkit #1 SMP Wed Mar 9 19:05:23 UTC 2022 x86_64" is not valid header value
```

**How to reproduce**  
```
<?php
$header = 'Linux f0f489981e90 5.10.104-linuxkit 1 SMP Wed Mar 9 19:05:23 UTC 2022 x86_64';

$client = new \GuzzleHttp\Client();
$response = $client->request('GET', 'https://enswyqyojtxm.x.pipedream.net', [
    'headers' => [
        'User-Agent' => 'testing/1.0',
        'Accept'     => 'application/json',
        'X-Foo'      => ['Bar', 'Baz'],
        'X-TEST'     => $header,
    ]
]);
```

**Possible Solution**  

**Additional context**  
I tested the whole 7.4 branch but the "problem" seems to be within ```guzzlehttp/psr7```. This line https://github.com/guzzle/psr7/blob/master/src/MessageTrait.php#L262

**Comment by it-can** [comment] 2022-03-20 18:55
Problem seems to be with the PSR7 library. Feel free to close this issue...

**Comment by GrahamCampbell** [comment] 2022-03-20 21:04
Duplicate of https://github.com/guzzle/psr7/issues/489.

**Closed by GrahamCampbell** 2022-03-20 21:04 UTC
