### ISSUE TITLE
Unable to handle uri with colon.

### ISSUE THREAD

**Issue by azusa0127** [guzzle/guzzle#1550] opened 2016-08-05 07:35 UTC
I have an api with colon in the uri syntax ('/document/demo/22:0'), which is not able to be correctly parsed by guzzle.

It is likely to be the issue of php function parse_url() as the error says 
"InvalidArgumentException: Unable to parse URI: /document/demo/22:0 in /var/www/html/demo/vendor/guzzlehttp/psr7/src/Uri.php:53 Stack trace: ..."

Not sure if this is a general issue or a special case in php7.

Versions:
guzzle 6.2.1
php 7.0.8-0ubuntu0.16.04.2

**Comment by alexeyshockov** [comment] 2016-08-05 08:51
Please, check you full URI. Because a colon works well on both PHP 5.6 & 7.0:

```
$ psysh
Psy Shell v0.7.2 (PHP 7.0.8 — cli) by Justin Hileman
>>> parse_url('http://example.com/document/demo/22:0')
=> [
     "scheme" => "http",
     "host" => "example.com",
     "path" => "/document/demo/22:0",
   ]
```

**Comment by azusa0127** [comment] 2016-08-05 10:25
Thanks for helping, but strangely I'm still getting the issue reproduced consistently.

I'm pretty sure the colon was the problem maker as removing the colon leads to a successful request while putting it back reproduce the issue.

here is the full error message:

`InvalidArgumentException: Unable to parse URI: /document/ubccourse16w/22:0 in /var/www/html/demo/vendor/guzzlehttp/psr7/src/Uri.php:53 Stack trace: #0 /var/www/html/demo/vendor/guzzlehttp/psr7/src/functions.php(59): GuzzleHttp\Psr7\Uri->__construct('/document/ubcco...') #1 /var/www/html/demo/vendor/guzzlehttp/guzzle/src/Client.php(142): GuzzleHttp\Psr7\uri_for('/document/ubcco...') #2 /var/www/html/demo/vendor/guzzlehttp/guzzle/src/Client.php(115): GuzzleHttp\Client->buildUri('/document/ubcco...', Array) #3 /var/www/html/demo/vendor/guzzlehttp/guzzle/src/Client.php(129): GuzzleHttp\Client->requestAsync('GET', '/document/ubcco...', Array) #4 /var/www/html/demo/test.php(22): GuzzleHttp\Client->request('GET', '/document/ubcco...', Array) #5 /var/www/html/demo/test.php(48): OriendbAPI->__http_get('/document/ubcco...') #6 /var/www/html/demo/test.php(67): OriendbAPI->_api_document_get('22:0') #7 /var/www/html/demo/test.php(83): OriendbAPI->getDocument('22:0') #8 {main}message`

Would that matter if I'm running the code on nginx + php-fpm?

**Comment by azusa0127** [comment] 2016-08-06 01:54
Thanks for helping, @alexeyshockov. After your inspiration I've done some more debugs and find out the $uri passed in to the parse_url() function was the string "/document/demo/22:0", not the full string with host and port. 

As you may confirm the result in [Repl.it](https://repl.it/languages/php), it seems like parse_url() had treated the colon as the delimiter for <host>:<port>

```
PHP 7.0.8 (cli) (built: Jun 23 2016 23:39:14) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
   parse_url("/document/demo/22:0");
=> false
   parse_url("/document/demo/22");
=> {"path":"\/document\/demo\/22"}
```

So, I end up with solving my case by passing in the full uri with host and ports included. But this is a bug either of faulty implementation parse_url() from php, or an improper usage of parse_url() of guzzle.

Should I change this issue into a bug report?

**Comment by alexeyshockov** [comment] 2016-08-08 09:20
I'm not sure if it's a bug, because URL parsers in other languages have the same behaviour.

```
$ scala
Welcome to Scala 2.11.8 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_66).
Type in expressions for evaluation. Or try :help.

scala> val u = new java.net.URL("/document/demo/22:0")
java.net.MalformedURLException: no protocol: /document/demo/22:0
  at java.net.URL.<init>(URL.java:586)
  at java.net.URL.<init>(URL.java:483)
  at java.net.URL.<init>(URL.java:432)
  ... 32 elided
```

I can not find the exact chapter in the RFC now, but it seems not a bug.

**Comment by Tobion** [comment] 2016-08-16 21:46
There is already a long-standing bug report for that on PHP. IMO this can be closed as it should be fixed by php. Also the problem is more in https://github.com/guzzle/psr7 and not here.

**Comment by mtdowling** [comment] 2016-08-24 22:20
Agreed with Tobion -- this is a PHP stdlib issue.

**Closed** 2016-08-24 22:19 UTC

**Comment by c960657** [comment] 2016-09-29 18:47
FWIW, the PHP bug is this:
[#71646: parse_url fails to parse relative url with port-like string in url](https://bugs.php.net/bug.php?id=71646)

Previously reported in [#55511 broken parse_url](https://bugs.php.net/bug.php?id=55511), but that was marked as _Bogus_.

**Comment by brayandev2** [comment] 2017-04-20 17:20
I was able to solve this issue putting the URL like this:

```/api/v1/rest/account/advertiser:1```
 
for this:

```'/api/v1/rest/account/advertiser:1**?**```
