### ISSUE TITLE
GuzzleException should extend Throwable

### ISSUE THREAD

**Issue by maikelsalazar** [guzzle/guzzle#2196] opened 2018-11-13 14:34 UTC
Working with IDEs (i.e PHPStorm) will always mark a warning because you don't catch a `GuzzleException`. But, you can't catch anything that doesn't extend `Throwable`. `GuzzleException` should extend `Throwable`.

**Comment by gmponos** [comment] 2018-11-13 14:36
duplicate of https://github.com/guzzle/guzzle/issues/2184 ???

**Comment by maikelsalazar** [comment] 2018-11-13 14:37
Oh, yes, thank you @gmponos!

**Closed** 2018-11-13 15:36 UTC
Labels: resolution/duplicate
