### ISSUE TITLE
guzzle hangs forever on some urls

### ISSUE THREAD

**Issue by melfa** [guzzle/guzzle#975] opened 2015-02-08 22:18 UTC
My code is:

            $response = (new Client)->get($url, [
                'timeout' => 15,
                'connect_timeout' => 5,
                'cookies' => new CookieJar,
                'verify' => false,
                'stream' => true,
                'headers' => [
                    'User-Agent' => self::USER_AGENT . ' ' . self::ROBOT_USER_AGENT,
                    'Accept' => join(',', self::$validContentTypes),
                    'Accept-Language' => 'ru-RU,ru;q=0.8,en-US;q=0.6,en;q=0.4',
                ],
            ]);

            // at this point no response and no timeout exception
            $response->getBody()->getContents();

URL's are:
http://www.zdravmedinfo.com/mednews.html?__rmid=lechenie-sarkomy-yuinga-mozhno-975145977.html&xrs=RebelMouse_tw
http://blog.weprotestify.com/
(i got over 10 bad urls of 340425 good from twitter, facebook links parser)

My suggestion is stream_get_contents in blocking mode blocks thread forever.

My workaround is:

                $streamMeta = $response->getBody()->getMetadata();
                $maxDataNeeded = self::PAGE_SIZE_LIMIT * 1024 * 1024;
                $limit = isset($streamMeta['unread_bytes']) ? $streamMeta['unread_bytes'] : $maxDataNeeded;
                if ($limit > $maxDataNeeded) {
                    $limit = $maxDataNeeded;
                }
                $body = (new LimitStream($response->getBody(), $limit))->getContents();

Checked on guzzlehttp/guzzle 5.1.0, 5.2.0, PHP 5.5.10-1

**Comment by mtdowling** [comment] 2015-02-12 05:56
This problem is caused by the fact that the PHP stream wrapper doesn't work well with `stream_get_contents` when using HTTP/1.1 responses that have no Content-Length header. I'm not sure why, but that's why it's failing. You can reproduce this simply using PHP's stream wrapper:

```php
<?php
require 'vendor/autoload.php';

$url = 'http://www.zdravmedinfo.com/mednews.html?__rmid=lechenie-sarkomy-yuinga-mozhno-975145977.html&xrs=RebelMouse_tw';
$ctx = stream_context_create(['http' => ['protocol_version' => 1.1]]);
$r = fopen($url, 'r', false, $ctx);
// The following will hang forever.
echo stream_get_contents($r);
```

If you remove the stream context and use HTTP/1.0, then it will work just fine.

You can change the protocol version used by Guzzle using the `version` request option. I think this will solve your problem until this (what looks like a bug) is fixed in PHP.

**Comment by melfa** [comment] 2015-02-13 09:12
Thank you for answer!
I need only a first 1Mbyte of stream, so my solution satisfy me as well, but thank you any way.

**Comment by melfa** [comment] 2015-02-13 09:12
I should close issue?

**Comment by mtdowling** [comment] 2015-02-13 18:14
Yeah, I think this can be closed now. I'll comment back here if I find out anything interesting about this bug.

**Closed by mtdowling** 2015-02-13 18:14 UTC
