### ISSUE TITLE
How to cancel url-encode in query?

### ISSUE THREAD

**Issue by blsn** [guzzle/guzzle#1758] opened 2017-02-27 08:12 UTC
I need to cancel url-encode the "=" character in ClientName=John

API doc:
http://api.wordbee-translator.com:32570/projects?token=xxx&filter=ClientName='John'

The GET Method that I use to implement with filter:
```
$resp = $project->request('GET', 'projects', [
        'query' => [
            'token' => $tokenId,
            'filter' => 'ClientName=John'
        ]
]);
```
I get response '400 Bad Request' due to the %3D characters as appears below:
https://api.wordbee-translator.com:32570/projects?token=xxx&filter=ClientName%3DJohn

How to fix it?

**Comment by Konafets** [comment] 2017-02-27 17:07
You don't provide _John_ as a `String` to the API:
`&filter=ClientName='John'` vs `'filter' => 'ClientName=John'`. Mind the missing `''` around _John_

**Comment by blsn** [comment] 2017-02-28 07:33
Thank you for your comment, I still get the same error.
The issue is how to cancel url-encode the "=" character.

For example I tried the following:
`'filter=ProjectId'  => 77`
**uri result**:
https://api.wordbee-translator.com:32570/projects?token=xxx&filter%3DProjectId=77

And I tried the following:
```
'filter' => [       
   'ProjectId' => 77    
] 
```
**uri result**:
https://api.wordbee-translator.com:32570/projects?token=xxx&filter%5BProjectId%5D=77

How to get the effective uri as follows?
https://api.wordbee-translator.com:32570/projects?token=xxx&filter=ProjectId=77

**Comment by sagikazarmark** [comment] 2017-02-28 22:59
This is a duplicate of https://github.com/guzzle/guzzle/issues/1696#issuecomment-280092334

Please see the answer there.

**Comment by Lomaster** [comment] 2017-04-05 08:54
One more question.

How can I use this query and cancel urlencode symbols : " (quote) in a request?
['query' => ['Query' => Gtin:"027917022710"]]

Guzzle transformates it to ?Query=Gtin%3A%22648575210037%22

**Comment by sagikazarmark** [comment] 2017-04-07 20:10
You can't, it's intended. You have to decode it on the receiver side.

**Closed** 2017-04-07 20:10 UTC
Labels: Question

**Comment by rafapaulin** [comment] 2018-02-16 13:24
Intended, but sometimes we are using 3rd party apis which does not do the decode... how to solve the encoding in that case?

**Comment by drtechie** [comment] 2018-02-17 12:08
There must be some option to prevent URL encoding of the query string.

The issue I am facing is as follows.

```php
       $paramsJoined = array();

        foreach($api_details['query'] as $param => $value) {
            $paramsJoined[] = "$param=$value";
        }

        $query = implode('&', $paramsJoined);

        $response = $client->get($api_details['url'], [
            'query' => $query,
            'on_stats' => function (TransferStats $stats) use (&$url) {
                $url = $stats->getEffectiveUri();
            }
        ]);
```

```php
...

'url' => Config::get('apiURL'),
'query' => array(
     'q' => $search_string.' AND prism.creationDate>='.$created_date,
     'maximumRecords' => 100,
      'httpAccept' => 'application/json'
)

...
```

The actual query that I need

```
q=keyword AND prism.creationDate>=2017
```

What Guzzle's effective URI is

```
q=keyword%2520AND%2520prism.creationDate%253E%3D2017
```
Expected
```
q=keyword%20AND%20prism.creationDate%3E%3D2017
```

What I have tried

Passing the array (instead of joined params).
Appending '?'.$query
Keeping the encoded string -> this results in characters like % getting encoded again.

**Comment by tomsihap** [comment] 2019-06-25 19:04
Any updates about this issue ?

**Comment by kalesh13** [comment] 2019-07-15 07:44
Looks like I can't use Guzzle for Paypal API calls.

https://developer.paypal.com/docs/classic/payflow/integration-guide/#do-not-url-encode-name-value-parameter-data

There should be some option to disable url encoding.

**Comment by gseidel** [comment] 2020-02-02 08:36
There is a workaround. The Problem is the `GuzzleHttp\Psr7\Uri` class which apply the encoding to the URI. Since `GuzzleHttp\Psr7\Uri` implements the Psr7 Interface `Psr\Http\Message\UriUriInterface`, you can create your own Uri class and pass it to a Guzzle request.

```php
use Psr\Http\Message\UriInterface;

// I didn't test it, it's just to demonstrate how a workaround could look like
MyUrl implements UriInterface
{
    private $parts;

    public function __construct($uri)
    {
        $this->parts = parse_url($uri);
    }

    public function getPath()
    {
        return $this->parts['path'];
    }

    public function getQuery()
    {
        return $this->parts['query'];
    }

    // you have to implement the other functions
}
```

```php
use MyUrl;
$client->request('GET', new MyUrl('projects'));

**Comment by DecolipAkira** [comment] 2022-03-24 02:36
# I had the same problem, through this code:

```php
public function getEntries($accessToken, $type) {
    $request = $this->guzzle->get('/entries', [
        'query' => [
            'filters' => 'type::in(' . $type . ')'
        ],
        'headers' => [
            'Content-Type'  => 'application/json',
            'Authorization' => 'Oauth ' . $accessToken
        ]
    ]);

    return $request->getBody();
}
```
My return was:

`https://api.moip.com.br/entries?0=filters%3Dtype%3A%3Ain%28COMMISSION%29`
> Note: This was not my real problem, I passed the incorrect url, the correct one would be **'/v2/entries'** 😂😂

# Fortunately I found a solution to this problem!

Solution:

```php
use GuzzleHttp\Query;

public function getEntries($accessToken, $type) {
    $request = $this->guzzle->get('/v2/entries', [
        'query' => Query::fromString('filters=type::in(' . $type . ')', false),
        'headers' => [
            'Content-Type'  => 'application/json',
            'Authorization' => 'Oauth ' . $accessToken
        ]
    ]);

    return $request->getBody();
}
```

**The real solution lies in the method:**

```php
Query::fromString($query, $urlEncoding = true)
```

### I'm glad I could help them!

Regards,
**Decolip Akira.**

**Comment by willnjl** [comment] 2023-07-07 10:50
**Simple work around:**

 just interpolated my url parms into the url myself and sent the request worked fine.

**Comment by jamesmacwhite** [comment] 2023-12-22 10:15
I have found Guzzle 7 to be most problematic with the likes of Microsoft APIs when using OData, which have some exotic URL query parameters e.g. filters `$filter=something eq 'value'`. The space and single quote being encoded will break it, as it is not handled on the server end in that way. It goes beyond just query parameters, it's the whole URI value.

There is also information around disabling encoding but it's for older Guzzle versions, which don't apply to Guzzle 7. I think the only real solution is providing a Uri class that controls what happens, otherwise you'll just have issues, if you need specific control.
