### ISSUE TITLE
use localhost server for interface request. will appear always error

### ISSUE THREAD

**Issue by ishwy** [guzzle/guzzle#2027] opened 2018-03-16 05:34 UTC
| Q            | A
| ------------ | ---
| Bug?         | don't know
| New Feature? | yes
| Version      | "guzzlehttp/guzzle": "~6.0",

#### Actual Behavior

What is the actual behavior?
use localhost server for interface request. will appear always error, nginx error **504 Gateway Time-out**  : 
ex: use 192.168.10.6 deed request url server address. looping HBL thread.
2018/03/16 13:26:00 [error] 2848#13436: *15 upstream timed out (10060: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond) while reading response header from upstream, client: 127.0.0.1, server: tv.cc, request: "GET /aaa/cccc HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "tv.cc"

But, use products no Exception

#### Expected Behavior

What is the behavior you expect?
use localhost address request o exception

#### Steps to Reproduce

What are the steps to reproduce this bug? Please add code examples,
screenshots or links to GitHub repositories that reproduce the problem.
code:
```
<?php
$client = new \GuzzleHttp\Client();
$response = $client->request('GET', '192.168.10.1', [
    "timeout" => 3000
]);

echo $response->getStatusCode(), "\n";
echo $response->getBody();
```
php5.6
nginx:1.11.5

#### Possible Solutions

If you have already ideas how to solve the issue, add them here.
(remove this section if not needed)

**Comment by Nyholm** [comment] 2018-03-16 06:02
Thank you for this issue. 
However, this does not look like there is anything wrong with Guzzle. If you get a proper HTTP response (like 504) I would start to investigate your server and gateway. 

Im closing this issue. Please refer to other resources like StackOverflow if you need help.

**Closed by Nyholm** 2018-03-16 06:02 UTC

**Comment by ishwy** [comment] 2018-03-16 06:08
wait , wait.
but, The same code. merely request url address unlikeliness.  And, localhost url  is normal. 
so, I dont'know , are Guzzle or me a problem of.
thx.

**Comment by Nyholm** [comment] 2018-03-16 06:10
Again, it is not Guzzle. It is your server settings on localhost that is the issue.

**Comment by sagikazarmark** [comment] 2018-03-16 10:01
The returned response indicates that your server responded, this the request itself is successful. The response code indicates that something went wrong on server side (most probably your nginx server couldn't connect to php-fpm).

The fact that it works locally is irrelevant in this case as the problem is on the server side.

**Comment by ishwy** [comment] 2018-03-21 04:24
@sagikazarmark But The problem is my local server . If direct use local curl visit ,this can be.
`curl http://localhost/q101/code?uid=990006
{"code":200,"message":"","data":{"code":"lL170620"}}`

If I put this url in there.  e.g.
`$client->request('GET', '192.168.10.1', [
    "uid" => 3000
]);`
Just keep asking , until nginx 504 Time out

**Comment by ishwy** [comment] 2018-03-21 08:54
@sagikazarmark oh, yes. problem solved .  causes of problem is nginx config of fastcgi_pass port the same....   cause a blockage.  thanks very much

**Comment by ivalsdtech** [comment] 2020-12-08 09:31
@ishwy can you share the nginx config?

**Comment by ishwy** [comment] 2020-12-08 09:35
@ivalsdtech it's gone, the main thing is that  ```fastcgi_pass```
