### ISSUE TITLE
Exceptions truncated after 120 characters

### ISSUE THREAD

**Issue by Azeirah** [guzzle/guzzle#2091] opened 2018-06-19 11:18 UTC
| Q            | A
| ------------ | ---
| Bug?        | no|yes
| New Feature? | yes
| Version      | Specific version or SHA of a commit

#### Actual Behavior

When a guzzle Exception occurs, and you call `$e->getMessage()`, the message will be truncated to 120 characters max.

#### Expected Behavior

I expect the 120 characters limit to be a **default**, but to be configurable in some global manner. 

#### Possible Solutions

One way would be to add an option, "exception_message_limit".

Something like this would be nice. Set it once, and then that value will be used instead of the default of 120.

```
GuzzleHttp::set_config(["exception_message_limit" => 1024]);
```

[code](https://github.com/guzzle/guzzle/blob/b4e2ffb457f37d629a6ec9b72fd0d9c85f3dfe2c/src/Exception/RequestException.php#L139)

**Comment by sagikazarmark** [comment] 2018-09-28 16:50
Duplicate of #1722

A decision has been made that this won't be implemented. If you need the whole response body, you can get it from the exception.

**Closed** 2018-09-28 16:50 UTC
Labels: resolution/duplicate
