### ISSUE TITLE
How to send to post request with cookies in header.

### ISSUE THREAD

**Issue by amankumarglobussoft** [guzzle/guzzle#1549] opened 2016-08-05 05:20 UTC
I am trying to Login into LinkedIn by guzzle, by send the post request by I am unable to log-In.
Here Is My Code:

```
$response = $client->post('https://www.linkedin.com/uas/login-submit', [
            'headers' => [
                'User-Agent' => 'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36',
                'Content-Type' => 'application/x-www-form-urlencoded',
                'Accept' => '*/*',
                'Accept-Language' => 'en-US,en;q=0.8,hi;q=0.6,und;q=0.4',
                'cookies' => true
            ],
            'form_params' => ['body' => 'isJsEnabled=true&source_app=&tryCount=&session_key=nitishkumar%40globussoft.in&session_password=*******&signin=Sign%20In&session_redirect=&trk=hb_signin&loginCsrfParam="' . $this->loginCsrfParam . '"&fromEmail=&csrfToken="' . $this->csrfToken . '"&sourceAlias="' . $this->sourceAlias . '"']
        ]);

        echo $response->getBody();
```
I think I am not able to set the cookie.

**Comment by mtdowling** [comment] 2016-08-05 05:41
> Have you looked at the cookies section of the docs?

http://docs.guzzlephp.org/en/latest/request-options.html#cookies

Alternatively, you can just manually create the header and set it in the "headers" option.

**Comment by amankumarglobussoft** [comment] 2016-08-05 05:51
@mtdowling  Yes I looked into the docs and I have tried the code
`$jar = new \GuzzleHttp\Cookie\CookieJar();`
And in header I have put the code like:
```
$response = $client->post('https://www.linkedin.com/uas/login-submit', [
            'headers' => [
                'User-Agent' => 'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36',
                'Content-Type' => 'application/x-www-form-urlencoded',
                'Accept' => '*/*',
                'Accept-Language' => 'en-US,en;q=0.8,hi;q=0.6,und;q=0.4',
                'cookies' => $jar
            ],
            'form_params' => ['body' => 'isJsEnabled=true&source_app=&tryCount=&session_key=nitishkumar%40globussoft.in&session_password=*******&signin=Sign%20In&session_redirect=&trk=hb_signin&loginCsrfParam="' . $this->loginCsrfParam . '"&fromEmail=&csrfToken="' . $this->csrfToken . '"&sourceAlias="' . $this->sourceAlias . '"']
        ]);

        echo $response->getBody();
```

But Failed.
I have tried same code for facebook and got logged in  but not in LinkedIn

**Comment by mtdowling** [comment] 2016-08-05 06:21
You put cookies in the headers array, but it needs to be in the outer array as a sibling to headers.

**Comment by amankumarglobussoft** [comment] 2016-08-05 06:38
Ok Now I am tried to set the cookie outside the header but still the same.
```
$response = $client->post('https://www.linkedin.com/uas/login-submit', [
            'headers' => [
                'User-Agent' => 'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36',
                'Content-Type' => 'application/x-www-form-urlencoded',
                'Accept' => '*/*',
                'Accept-Language' => 'en-US,en;q=0.8,hi;q=0.6,und;q=0.4',
               
            ],
           'cookies' => $jar,
            'form_params' => ['body' => 'isJsEnabled=true&source_app=&tryCount=&session_key=nitishkumar%40globussoft.in&session_password=*******&signin=Sign%20In&session_redirect=&trk=hb_signin&loginCsrfParam="' . $this->loginCsrfParam . '"&fromEmail=&csrfToken="' . $this->csrfToken . '"&sourceAlias="' . $this->sourceAlias . '"']
        ]);

        echo $response->getBody();
```

**Comment by mtdowling** [comment] 2016-08-24 22:13
`form_params` looks off here. If you want to send the body already encoded as form params, then just set the `body` request option. You're currently nesting an encoded body under `form_params`. Closing as this is not a bug in Guzzle.

**Closed by mtdowling** 2016-08-24 22:13 UTC
