### ISSUE TITLE
Infinite loop using CurlMulti handler

### ISSUE THREAD

**Issue by kkopachev** [guzzle/guzzle#1940] opened 2017-10-18 00:43 UTC
| Q            | A
| ------------ | ---
| Bug?         | yes
| New Feature? | no
| Version      | 6.3.0

#### Actual Behavior

Running a lot of requests. At some point sometimes it stuck in infinite loop.

#### Expected Behavior

Return an error? Or maybe finish requests?

#### Steps to Reproduce

Hard to repro, since only happens sometimes. I downloading pages mentioned in sitemap. Basically crawling website. Task runs once a day and was fine for 5 days and now process is stuck.
PHP 7.1.9 (cli) (built: Sep 15 2017 00:02:11) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
php is from official docker image php:7 , no extra extensions.
#### Possible Solutions

ltrace shows (repeatedly):
```
select(23, 0x7ffd1448e370, 0x7ffd1448e3f0, 0x7ffd1448e470)                                       = 0
curl_multi_perform(0x55d5d171a500, 0x7ffd1448e4f0, 2, 3)                                         = 0
curl_multi_info_read(0x55d5d171a500, 0x7ffd1448e4cc, 11, 0)                                      = 0
curl_multi_fdset(0x55d5d171a500, 0x7ffd1448e370, 0x7ffd1448e3f0, 0x7ffd1448e470)                 = 0
select(23, 0x7ffd1448e370, 0x7ffd1448e3f0, 0x7ffd1448e470)                                       = 0
curl_multi_perform(0x55d5d171a500, 0x7ffd1448e4f0, 2, 3)                                         = 0
curl_multi_info_read(0x55d5d171a500, 0x7ffd1448e4cc, 11, 0)                                      = 0
curl_multi_fdset(0x55d5d171a500, 0x7ffd1448e370, 0x7ffd1448e3f0, 0x7ffd1448e470)                 = 0
select(23, 0x7ffd1448e370, 0x7ffd1448e3f0, 0x7ffd1448e470)                                       = 0
curl_multi_perform(0x55d5d171a500, 0x7ffd1448e4f0, 2, 3)                                         = 0
curl_multi_info_read(0x55d5d171a500, 0x7ffd1448e4cc, 11, 0)                                      = 0
curl_multi_fdset(0x55d5d171a500, 0x7ffd1448e370, 0x7ffd1448e3f0, 0x7ffd1448e470)                 = 0
```
maybe related to https://github.com/guzzle/guzzle/pull/1933 ?

I still have task running in that infinite loop, so might run some straces or whatever needed to debug.

**Comment by tomzx** [comment] 2017-12-08 21:03
Hello,

You should provide some code in order to make it easier for others to help you debug your issue.

Thanks!

**Comment by kkopachev** [comment] 2017-12-21 20:37
@tomzx sure. It's quite simple code.
```php

use GuzzleHttp\Client;
use function GuzzleHttp\Promise\each_limit;

require 'vendor/autoload.php';

$client = new Client();

$generator = function (array $urls) use ($client) {
    foreach ($urls as $url) {
        yield $client->requestAsync('GET', $url)->then(function() use($url) {
            echo 'requested ',  $url, PHP_EOL;
        });
    }
};

$urls = [
    'https://httpbin.org/get',
    // ... 
];

each_limit($generator($urls), 20)->wait();
```

suppose it has a lot of urls in that array. There is some chance it'll hang. 
In my situation I was using single client for many requests. About 1M requests to made each day. It's a cron job and starts at the same time each day. Process was stuck in the loop once per week.
I worked it around by creating new client for each 30k requests or so and that was working better for few weeks, maybe even a month, but still stuck at some point. 

Recently we found out that another process, which was using AWS SDK also hang. No concurrent requests has being made in that job, so does not look like it's an issue with `each_limit`. `strace`/`ltrace` showed the same loop as in the issue above.

**Comment by kkopachev** [comment] 2017-12-21 21:07
Additionally, `lsof` shows connection as `ESTABLISHED` (with file descriptor my process is polling), `tcpdump` shows no activity to that host.

**Comment by kkopachev** [comment] 2017-12-22 21:19
Looked up further and found that default timeout/connect_timeout for `CurlHandler` is not set, meaning it will wait forever. On the other hand, `StreamHandler` with default settings will wait [default-socket-timeout ini setting](http://php.net/manual/en/filesystem.configuration.php#ini.default-socket-timeout) and does not look like there is a way to make it wait forever, since it [only cares about positive numbers](https://github.com/guzzle/guzzle/blob/master/src/Handler/StreamHandler.php#L416-L418)

Back to the problem with hanging request.
So, my theory is CurlHandler does not have default timeout and will wait indefinitely for response to come. In some rare cases TCP connection dropped by remote peer, but it fails to notify client side about that event or packed lost in transmission somehow. At that point client thinks connection is still alive, it's waiting for some data to come and just unable to figure out that there is no connection. 
I thought that there must be TCP keepalive packets going back and forth to distinguish between `no-data` and `dropped-connection` situations. Host OS has tcp_keepalive configured. However CURL [by default disables](https://curl.haxx.se/libcurl/c/CURLOPT_TCP_KEEPALIVE.html) these options (or rather does not enable). I figured that out via `netstat` output (last column):
```
root@52f701d7b310:/usr/src/app# netstat -atnpo                   
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name Timer
tcp        0      0 172.17.0.5:40192        52.x.x.x:443      ESTABLISHED 1/php            off (0.00/0/0)
tcp        0      0 172.17.0.5:49412        52.x.x.x:443        ESTABLISHED 1/php            off (0.00/0/0)
tcp       32      0 172.17.0.5:49052        54.x.x.x:443        CLOSE_WAIT  1/php            off (0.00/0/0)
..............
```

My proposal is to configure default curl timeout to reasonable number.
If that's not possible, then at least make StreamHandler consistent with CurlHandler implementation and make it possible to wait forever and use that as default.

**Comment by darinrandal** [comment] 2018-05-04 15:12
I'm having this issue as well. It seems that when processing tens of thousands of async requests just like above, I'll have one hang indefinitely every few days. I tried setting some timeouts but none of them helped.

```
$guzzleClient = new Client([
    'timeout' => 15,
    'connect_timeout' => 5,
]);

$awsClient->putObjectAsync([
    ...
    '@http' => [
        'timeout' => 15,
        'connect_timeout' => 5,
    ],
]);
```

**Comment by kkopachev** [comment] 2019-12-11 20:17
Ping @sagikazarmark @Nyholm  . Might be good idea to sync default timeouts for stream and curl handlers if you're planning next major version. Right now Curl handler waits infinitely, while Stream handler waits for default-socket-timeout ini setting seconds.

**Comment by Nyholm** [comment] 2019-12-11 20:41
Thank you for the ping. 

Hm. @darinrandal says it does not matter what your timeouts are, they still experience this problem. Right?

**Comment by kkopachev** [comment] 2020-01-07 17:22
While waiting for @darinrandal response, can you guys unify timeouts for CurlHandler and StreamHandler with documentation for 7.0 release?

**Comment by darinrandal** [comment] 2020-01-07 19:22
@Nyholm @kkopachev I am actually not sure if/when this was fixed, but I haven't seen the issue occurring recently. Currently my composer is just 6.*.

**Comment by Nyholm** [comment] 2020-01-07 19:34
@kkopachev could you open an new issue with that?

@darinrandal if you don’t see the issue anymore and we cannot reproduce it, then I have to close this issue. 

Feel free to open a new issue if someone still experience this.

**Closed by Nyholm** 2020-01-07 19:34 UTC

**Comment by angelsagredo** [comment] 2021-06-22 17:43
Same problem here. My code executes a pool with thousand of urls requests. It executes once a day. Sometimes, it get stuck and hangs forever with no reason. It not throw any exception.
When it happens, I need to kill the crontab process manually.

It's hard to reproduce because it only happens few times randomly.

I set timeouts but didn't work.

I'm using php 7.3 and guzzle 7.3.0
