### ISSUE TITLE
Breaking change in Guzzle 6 when receiving a 204 No Content response with no body

### ISSUE THREAD

**Issue by stevehill1981** [guzzle/guzzle#1432] opened 2016-03-18 10:33 UTC
After upgrading a client application to use Guzzle 6 (from our previous Guzzle 3), I've found an issue with how Guzzle handles responses with no content.

When we send a POST request to a specific API endpoint, we are expecting a 204 No Content response; in Guzzle 3, this is treated as successful. In Guzzle 6, the request is retried 3 times and then an exception is thrown:

```
[GuzzleHttp\Exception\RequestException]
  cURL error 0: The cURL request was retried 3 times and did not succeed. The most likely reason for the failure is that cURL was unable to rewind the body of the request and subsequent retries resulted in the same error. Turn on the debug option to see what went wrong. See https://bugs.php.net/bug.php?id=47204 for more information. (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)
```

This is happening because the API isn't just sending back an empty response - it's sending back no body content at all, as seen in the debug data I've captured:

```
* Hostname was NOT found in DNS cache
*   Trying 192.168.0.4...
* Connected to 192.168.0.4 (192.168.0.4) port 8765 (#0)
> POST /api/v1/general/controllers/3781220536545016/general/messaging/displayMessage HTTP/1.1
Host: 192.168.0.4:8765
Content-Length: 70

* upload completely sent off: 70 out of 70 bytes
* HTTP 1.0, assume close after body
< HTTP/1.0 204 No response
< Server: FontHTTP/1.0 Python/2.4.3
< Date: Fri, 18 Mar 2016 09:36:18 GMT
< Access-Control-Allow-Origin: *
* Closing connection 0
```

That causes us to run afoul of the change made in https://github.com/guzzle/guzzle/commit/15557b1523bf556a7d2ca8915a8a18cc261f06d4#diff-d158f796e08161a3de3578283a4298daR90.

The issue here is in how Guzzle handles responses which are technically invalid, but have worked in previous versions. We're unable to fix the API we're communicating with - it's a third-party system - so an ideal solution for us would be for Guzzle to treat these empty responses in the same way as it did prior to the above change.

For now, we've downgraded to version 5.3.0, which doesn't have this problem.

**Comment by mtdowling** [comment] 2016-03-21 17:10
I'm guessing the problem is that the server is closing the connection before sending the final "\r\n\r\n". This trips up the CurlFactory because it never knows when the headers are finished and doesn't create a response: https://github.com/guzzle/guzzle/blob/master/src/Handler/CurlFactory.php#L512.

Given a server that does send the final "\r\n\r\n", Guzzle is able to work correctly. I don't know what the solution to this would be, but I'm open to suggestions.

**Comment by stephenorr** [comment] 2016-03-22 13:08
Yeah, that sounds like exactly what we're seeing. It may just be that we have to ask the third-party to fix their API.

**Comment by stephenorr** [comment] 2016-03-22 13:58
Ok, I've been unable to get the results I was hoping for from PHP, so I've resorted to a very simple Python script.

This is available from the repo I've just created here: https://github.com/stephenorr/guzzle-1432-error-app

Hope that helps - I'll have a go at fixing the issue myself in a PR when I get chance.

**Comment by mtdowling** [comment] 2016-04-06 17:58
Sweet! Thanks for putting that together, and thanks for offering to help fix this!

**Comment by sagikazarmark** [comment] 2016-11-08 15:10
@stephenorr did you have the chance to take a look at this?

To be honest I am not 100% sure how to proceed with this. If the headers are not properly terminated we cannot be sure that the all the headers are actually properly received or the connection has just been terminated for any reasons. My concern is that accepting responses not complying with the HTTP spec might end up in a series of other weird bugs and issues. (Really network terminated connections with incomplete headers for instance)

> Although these responses are technically invalid according to the HTTP spec, they were treated as acceptable by versions of Guzzle prior to 6.0

I think that was only a side effect. Technically this is not a breaking change not only because of semver, but also because of this being a side effect.

So I am not sure this is bug (at least in Guzzle) and if it can be solved.

**Comment by stephenorr** [comment] 2016-11-09 16:01
Sadly, I've had no time whatsoever to try and take a further look at this.

I'm inclined to agree that it shouldn't be fixed; it is a regression, but as you say that's a side effect more than anything else. I'll try to work around it in our own application.

**Comment by sagikazarmark** [comment] 2016-11-09 17:41
All right, I am closing the issue then. Thanks for bringing it up, hopefully it can serve as a reference in the future. If you find a workaround, let us know, maybe we can place it in the docs or just leave it here. Thanks again.

**Closed** 2018-09-28 16:34 UTC
Labels: kind/bug

**Comment by itelmenko** [comment] 2020-02-06 06:23
Hello! How can I process this situation? 

> [GuzzleHttp\Exception\RequestException]                                                                                                              
  cURL error 0: The cURL request was retried 3 times and did not succeed.

Is there some solution how to get response?

**Comment by itelmenko** [comment] 2020-02-06 10:04
@sagikazarmark I think we need some way to work with such incorrect responses.

**Comment by sagikazarmark** [comment] 2020-02-06 11:24
@itelmenko your problem is unrelated to this issue.

Looking at the error message, this is probably an environmental issue.

Please open a separate issue and provide details of your environment.


After googling your problem this popped up: https://stackoverflow.com/questions/46323867/url-error-0-the-curl-request-was-retried-3-times-and-did-not-succeed

Any chance it might be related?

**Comment by itelmenko** [comment] 2020-02-06 11:34
@sagikazarmark problem cause is that server doesn't send the final "\r\n\r\n". And Guzzle stops with such error.
