### ISSUE TITLE
Undefined method 'getBoundary' on Client class

### ISSUE THREAD

**Issue by klikpaspor** [guzzle/guzzle#2718] opened 2020-06-30 05:52 UTC
This part of script contain **`Undefined method 'getBoundary'`**

```
$request = Psr7\modify_request($request, $modify);
        if ($request->getBody() instanceof Psr7\MultipartStream) {
            // Use a multipart/form-data POST if a Content-Type is not set.
            // Ensure that we don't have the header in different case and set the new value.
            $options['_conditional'] = Psr7\_caseless_remove(['Content-Type'], $options['_conditional']);
            $options['_conditional']['Content-Type'] = 'multipart/form-data; boundary='. $request->getBody()->getBoundary();
        }
```

**Comment by GrahamCampbell** [comment] 2020-06-30 09:22
Where is this code. In your app? I don't think we have a `getBoundary` method?

**Comment by GrahamCampbell** [comment] 2020-06-30 09:25
What is the type of `$request->getBody()` and what is the version of the guzzle psr7 package you have?

**Comment by klikpaspor** [comment] 2020-06-30 12:53
```
{
    "require": {
        "guzzlehttp/guzzle": "^6.5"
    }
}
```

[https://srv-file9.gofile.io/download/kUNJRv/Untitled.png](url)

**Comment by GrahamCampbell** [comment] 2020-06-30 13:49
Oh, that's just a bug in your IDE. Not an actual error...

**Comment by GrahamCampbell** [comment] 2020-06-30 13:49
The reason it's saying that is that getBoundary doesn't exist in general. It only exists if the body is a multipart stream.

**Comment by GrahamCampbell** [comment] 2020-06-30 13:50
This can't be statically detected.

**Comment by gmponos** [comment] 2020-06-30 13:51
Closing as this is not a bug. The instance of the stream is checked on the line before.

**Closed by gmponos** 2020-06-30 13:51 UTC
