### ISSUE TITLE
strtolower() expects parameter 1 to be string, int given

### ISSUE THREAD

**Issue by danielschweiger** [guzzle/guzzle#2911] opened 2021-07-03 07:52 UTC
**Guzzle version(s) affected**: 7.3
**PHP version**: 7.4.19
**cURL version**: 7.76.1

I get this error:

`strtolower() expects parameter 1 to be string, int given {"userId":1,"exception":"[object] (TypeError(code: 0): strtolower() expects parameter 1 to be string, int given at /home/vagrant/xxx/vendor/guzzlehttp/psr7/src/Utils.php:28)`

after calling the PayPal API with this command:

```
$response = Http::withHeaders([
            'Accept: application/json',
            'Content-Type: application/json',
        ])
        ->withToken($paypal_account->access_token)
        ->get(env('PAYPAL_LIVE_API_URL').'/v1/reporting/transactions', [
            'start_date' => $start_date,
            'end_date' => $end_date,
            'fields' => $fields,
            'balance_affecting_records_only' => 'N',
            'page_size' => $page_size,
            'page' => $page
        ]);
```

This happend after my composer update updated guzzlehttp from psr7 1.8.2 to 2.0.0.

In the meantime I fixed this for me adding this to my composer.json:

`"guzzlehttp/psr7": "1.8.2",`

**Comment by GrahamCampbell** [comment] 2021-07-03 16:12
Can you share the full stacktrace? You may need to install xdebug to show it if PHP is only showing the first line.

**Comment by danielschweiger** [comment] 2021-07-04 07:42
@GrahamCampbell 

`[2021-07-02 20:09:34] local.ERROR: strtolower() expects parameter 1 to be string, int given {"userId":1,"exception":"[object] (TypeError(code: 0): strtolower() expects parameter 1 to be string, int given at /home/vagrant/mypage.com/vendor/guzzlehttp/psr7/src/Utils.php:28)
[stacktrace]
#0 /home/vagrant/mypage.com/vendor/guzzlehttp/psr7/src/Utils.php(28): strtolower()
#1 /home/vagrant/mypage.com/vendor/guzzlehttp/psr7/src/Utils.php(189): GuzzleHttp\\Psr7\\Utils::caselessRemove()
#2 /home/vagrant/mypage.com/vendor/guzzlehttp/guzzle/src/Client.php(455): GuzzleHttp\\Psr7\\Utils::modifyRequest()
#3 /home/vagrant/mypage.com/vendor/guzzlehttp/guzzle/src/Client.php(326): GuzzleHttp\\Client->applyOptions()
#4 /home/vagrant/mypage.com/vendor/guzzlehttp/guzzle/src/Client.php(168): GuzzleHttp\\Client->transfer()
#5 /home/vagrant/mypage.com/vendor/guzzlehttp/guzzle/src/Client.php(187): GuzzleHttp\\Client->requestAsync()
#6 /home/vagrant/mypage.com/vendor/laravel/framework/src/Illuminate/Http/Client/PendingRequest.php(734): GuzzleHttp\\Client->request()
#7 /home/vagrant/mypage.com/vendor/laravel/framework/src/Illuminate/Http/Client/PendingRequest.php(668): Illuminate\\Http\\Client\\PendingRequest->sendRequest()
#8 /home/vagrant/mypage.com/vendor/laravel/framework/src/Illuminate/Support/helpers.php(234): Illuminate\\Http\\Client\\PendingRequest->Illuminate\\Http\\Client\\{closure}()
#9 /home/vagrant/mypage.com/vendor/laravel/framework/src/Illuminate/Http/Client/PendingRequest.php(682): retry()
#10 /home/vagrant/mypage.com/vendor/laravel/framework/src/Illuminate/Http/Client/PendingRequest.php(537): Illuminate\\Http\\Client\\PendingRequest->send()
#11 /home/vagrant/mypage.com/app/Repositories/PaypalRepository.php(370): Illuminate\\Http\\Client\\PendingRequest->get()
#12 /home/vagrant/mypage.com/app/Repositories/PaypalRepository.php(177): App\\Repositories\\PaypalRepository->get_raw_transactions()
#13 /home/vagrant/mypage.com/app/Jobs/ProcessPaypalTransactionImport.php(36): App\\Repositories\\PaypalRepository->import_transactions()
#14 /home/vagrant/mypage.com/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): App\\Jobs\\ProcessPaypalTransactionImport->handle()
#15 /home/vagrant/mypage.com/vendor/laravel/framework/src/Illuminate/Container/Util.php(40): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#16 /home/vagrant/mypage.com/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#17 /home/vagrant/mypage.com/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod()
#18 /home/vagrant/mypage.com/vendor/laravel/framework/src/Illuminate/Container/Container.php(651): Illuminate\\Container\\BoundMethod::call()
#19 /home/vagrant/mypage.com/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(128): Illuminate\\Container\\Container->call()
#20 /home/vagrant/mypage.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Bus\\Dispatcher->Illuminate\\Bus\\{closure}()
#21 /home/vagrant/mypage.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#22 /home/vagrant/mypage.com/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(132): Illuminate\\Pipeline\\Pipeline->then()
#23 /home/vagrant/mypage.com/vendor/laravel/framework/src/Illuminate/Foundation/Bus/Dispatchable.php(69): Illuminate\\Bus\\Dispatcher->dispatchNow()
#24 /home/vagrant/mypage.com/app/Observers/PaypalTransactionImportObserver.php(16): App\\Jobs\\ProcessPaypalTransactionImport::dispatchNow()
#25 /home/vagrant/mypage.com/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(412): App\\Observers\\PaypalTransactionImportObserver->created()
#26 /home/vagrant/mypage.com/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(237): Illuminate\\Events\\Dispatcher->Illuminate\\Events\\{closure}()
#27 /home/vagrant/mypage.com/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasEvents.php(189): Illuminate\\Events\\Dispatcher->dispatch()
#28 /home/vagrant/mypage.com/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1110): Illuminate\\Database\\Eloquent\\Model->fireModelEvent()
#29 /home/vagrant/mypage.com/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(930): Illuminate\\Database\\Eloquent\\Model->performInsert()
#30 /home/vagrant/mypage.com/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Relations/HasOneOrMany.php(267): Illuminate\\Database\\Eloquent\\Model->save()
#31 /home/vagrant/mypage.com/vendor/laravel/nova/src/Http/Controllers/ResourceStoreController.php(74): Illuminate\\Database\\Eloquent\\Relations\\HasOneOrMany->save()
#32 /home/vagrant/mypage.com/vendor/laravel/nova/src/Http/Controllers/ResourceStoreController.php(33): Laravel\\Nova\\Http\\Controllers\\ResourceStoreController->storeResource()
#33 /home/vagrant/mypage.com/vendor/laravel/framework/src/Illuminate/Database/Concerns/ManagesTransactions.php(29): Laravel\\Nova\\Http\\Controllers\\ResourceStoreController->Laravel\\Nova\\Http\\Controllers\\{closure}()
#34 /home/vagrant/mypage.com/vendor/laravel/framework/src/Illuminate/Database/DatabaseManager.php(388): Illuminate\\Database\\Connection->transaction()
#35 /home/vagrant/mypage.com/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(261): Illuminate\\Database\\DatabaseManager->__call()
#36 /home/vagrant/mypage.com/vendor/laravel/nova/src/Http/Controllers/ResourceStoreController.php(40): Illuminate\\Support\\Facades\\Facade::__callStatic()
#37 /home/vagrant/mypage.com/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): Laravel\\Nova\\Http\\Controllers\\ResourceStoreController->handle()
#38 /home/vagrant/mypage.com/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction()
#39 /home/vagrant/mypage.com/vendor/laravel/framework/src/Illuminate/Routing/Route.php(254): Illuminate\\Routing\\ControllerDispatcher->dispatch()
#40 /home/vagrant/mypage.com/vendor/laravel/framework/src/Illuminate/Routing/Route.php(197): Illuminate\\Routing\\Route->runController()
#41 /home/vagrant/mypage.com/vendor/laravel/framework/src/Illuminate/Routing/Router.php(695): Illuminate\\Routing\\Route->run()
#42 /home/vagrant/mypage.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()
#43 /home/vagrant/mypage.com/vendor/vyuldashev/nova-permission/src/ForgetCachedPermissions.php(23): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#44 /home/vagrant/mypage.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Vyuldashev\\NovaPermission\\ForgetCachedPermissions->handle()
#45 /home/vagrant/mypage.com/vendor/laravel/nova/src/Http/Middleware/Authorize.php(18): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#46 /home/vagrant/mypage.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Laravel\\Nova\\Http\\Middleware\\Authorize->handle()
#47 /home/vagrant/mypage.com/vendor/laravel/nova/src/Http/Middleware/BootTools.php(20): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#48 /home/vagrant/mypage.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Laravel\\Nova\\Http\\Middleware\\BootTools->handle()
#49 /home/vagrant/mypage.com/vendor/laravel/nova/src/Http/Middleware/DispatchServingNovaEvent.php(20): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#50 /home/vagrant/mypage.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Laravel\\Nova\\Http\\Middleware\\DispatchServingNovaEvent->handle()
#51 /home/vagrant/mypage.com/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(50): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#52 /home/vagrant/mypage.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle()
#53 /home/vagrant/mypage.com/vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authenticate.php(44): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#54 /home/vagrant/mypage.com/vendor/laravel/nova/src/Http/Middleware/Authenticate.php(31): Illuminate\\Auth\\Middleware\\Authenticate->handle()
#55 /home/vagrant/mypage.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Laravel\\Nova\\Http\\Middleware\\Authenticate->handle()
#56 /home/vagrant/mypage.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(78): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#57 /home/vagrant/mypage.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle()
#58 /home/vagrant/mypage.com/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#59 /home/vagrant/mypage.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle()
#60 /home/vagrant/mypage.com/vendor/laravel/framework/src/Illuminate/Session/Middleware/AuthenticateSession.php(58): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#61 /home/vagrant/mypage.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Session\\Middleware\\AuthenticateSession->handle()
#62 /home/vagrant/mypage.com/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#63 /home/vagrant/mypage.com/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest()
#64 /home/vagrant/mypage.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Session\\Middleware\\StartSession->handle()
#65 /home/vagrant/mypage.com/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#66 /home/vagrant/mypage.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle()
#67 /home/vagrant/mypage.com/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#68 /home/vagrant/mypage.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle()
#69 /home/vagrant/mypage.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#70 /home/vagrant/mypage.com/vendor/laravel/framework/src/Illuminate/Routing/Router.php(697): Illuminate\\Pipeline\\Pipeline->then()
#71 /home/vagrant/mypage.com/vendor/laravel/framework/src/Illuminate/Routing/Router.php(672): Illuminate\\Routing\\Router->runRouteWithinStack()
#72 /home/vagrant/mypage.com/vendor/laravel/framework/src/Illuminate/Routing/Router.php(636): Illuminate\\Routing\\Router->runRoute()
#73 /home/vagrant/mypage.com/vendor/laravel/framework/src/Illuminate/Routing/Router.php(625): Illuminate\\Routing\\Router->dispatchToRoute()
#74 /home/vagrant/mypage.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(166): Illuminate\\Routing\\Router->dispatch()
#75 /home/vagrant/mypage.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
#76 /home/vagrant/mypage.com/vendor/laravel/nova/src/Http/Middleware/ServeNova.php(24): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#77 /home/vagrant/mypage.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Laravel\\Nova\\Http\\Middleware\\ServeNova->handle()
#78 /home/vagrant/mypage.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#79 /home/vagrant/mypage.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#80 /home/vagrant/mypage.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle()
#81 /home/vagrant/mypage.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#82 /home/vagrant/mypage.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#83 /home/vagrant/mypage.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle()
#84 /home/vagrant/mypage.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#85 /home/vagrant/mypage.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle()
#86 /home/vagrant/mypage.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#87 /home/vagrant/mypage.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle()
#88 /home/vagrant/mypage.com/vendor/fruitcake/laravel-cors/src/HandleCors.php(38): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#89 /home/vagrant/mypage.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fruitcake\\Cors\\HandleCors->handle()
#90 /home/vagrant/mypage.com/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#91 /home/vagrant/mypage.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fideloper\\Proxy\\TrustProxies->handle()
#92 /home/vagrant/mypage.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#93 /home/vagrant/mypage.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(141): Illuminate\\Pipeline\\Pipeline->then()
#94 /home/vagrant/mypage.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(110): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#95 /home/vagrant/mypage.com/public/index.php(52): Illuminate\\Foundation\\Http\\Kernel->handle()
#96 {main}
"} `

**Comment by GrahamCampbell** [comment] 2021-07-04 14:46
Oh, you're call to `withHeaders` is wrong.

**Comment by GrahamCampbell** [comment] 2021-07-04 14:47
```
Http::withHeaders([
            'Accept' =>' application/json',
            'Content-Type' => 'application/json',
        ])
```

**Comment by GrahamCampbell** [comment] 2021-07-04 14:47
cc @Nyholm we could add some type checking higher up to stop this kind of user error causing crashes in the internals.

**Comment by danielschweiger** [comment] 2021-07-05 15:24
@GrahamCampbell 

whats wrong with my `withHeaders`?

that way it works with 1.8.2

**Comment by GrahamCampbell** [comment] 2021-07-05 18:18
> that way it works with 1.8.2

That was just by chance. 2.0.0 is more strict.

**Comment by Nyholm** [comment] 2021-07-17 17:06
I think this should be fixed in Laravel. 
I tried to dig around in the code. I could not reproduce the issue with the latest version. 

I have added a PR to throw an exception if you are using all wrong headers. See https://github.com/guzzle/guzzle/pull/2916

**Closed by Nyholm** 2021-07-17 17:06 UTC
