### ISSUE TITLE
Default queries gets dropped if specifying queries

### ISSUE THREAD

**Issue by etu** [guzzle/guzzle#2118] opened 2018-08-01 12:18 UTC
| Q            | A
| ------------ | ---
| Bug?         | maybe
| New Feature? | no
| Version      | 6.3.3

#### Actual Behavior
When defining default parameters when creating a client and then using that client to define additional parameters. The default parameters defined get's dropped.

#### Expected Behavior
I expected to keep the default parameters and only overwrite a default parameter if I define the same key with a different value than the default parameter. I also expect a default parameter to be dropped if I define the same key with a null value.

#### Steps to Reproduce
```php
<?php
require('vendor/autoload.php');

use GuzzleHttp\Client;

$client = new GuzzleHttp\Client([
    'base_uri' => 'https://example.com/',
    'query' => [ 'version' => 'project-version-name' ],
    'headers' => [
        'X-Internal-Header' => 'my-internal-header',
    ],
]);

// Actual behavior is that the default query parameters get replaced when I specify query parameters here.
$response = $client->request('GET', 'some-path-under-base', [
    'query' => [ 'some-query-param' => 'query-value' ],
]);

// This is the workaround I found but it seems to be very unnecessary and easy to miss to cause errors
$response = $client->request('GET', 'some-path-under-base', [
    'query' => $client->getConfig('query') + [ 'some-query-param' => 'query-value' ],
]);
```

This wasn't an issue before 6.x. And I'm doing a big migration.

The actual drop of the default parameters happens here:
https://github.com/guzzle/guzzle/blob/master/src/Client.php#L236

**Comment by sagikazarmark** [comment] 2018-09-28 16:29
As far as I can see, this is a duplicate of #2149. Please see my answer there.

**Closed** 2018-09-28 16:30 UTC
Labels: kind/support, resolution/duplicate, resolution/invalid
