### ISSUE TITLE
All Cookie documentation is gone

### ISSUE THREAD

**Issue by ghost** [guzzle/guzzle#1763] opened 2017-03-02 17:50 UTC
Example: http://docs.guzzlephp.org/en/latest/request-options.html?highlight=cookie#cookies

Everything is gone. Search the whole docs for "cookie" and "cookies":

- http://docs.guzzlephp.org/en/latest/search.html?q=cookie&check_keywords=yes&area=default
- http://docs.guzzlephp.org/en/latest/search.html?q=cookies&check_keywords=yes&area=default

None of the links work. The cookies have been eradicated from the docs. ;-) Seems to have been this way for a while. 5.3 docs lack it too.

**Comment by mtdowling** [comment] 2017-03-03 03:10
Can you elaborate? How are the docs gone? You provided a link directly to the cookie docs.

**Comment by SteveJobzniak** [comment] 2017-03-03 15:46
@mtdowling Ehhh... I see no cookies section in the example link on my desktop, Google Chrome and Safari on a Mac. Neither shows any cookie section.

But Safari on iOS on an iPhone 5 is able to see it...

This is what the page looks like on desktop (cookies is supposed to be between these two items):

![screen shot 2017-03-03 at 16 46 15](https://cloud.githubusercontent.com/assets/22373193/23557648/f9aabea6-0030-11e7-8fdf-be7fc1f10db7.png)

**Comment by sagikazarmark** [comment] 2017-03-03 20:06
Can you see it in the navigation?

**Comment by Konafets** [comment] 2017-03-03 20:17
Hey @SteveJobzniak, sounds like a dupe of #1401 .

**Comment by SteveJobzniak** [comment] 2017-03-03 21:13
Oh I think it's the Prebake adblock filter which hides all EU cookie notices.

This shows the danger of calling the section "cookies" and making it a prime target of various browser addons...

I guess renaming it is out of the question since the docs are autogenerated?

**Comment by Konafets** [comment] 2017-03-04 08:53
> This shows the danger of calling the section "cookies" and making it a prime target of various browser addons...

Mhhm, let me imagine the issues which will be open if the section was named "Kekse", "Småkage" or "biscuits". `Cookie` is a well-known named for the concept it describes. 

But because it interests me: Which name would you suggest for the concept the term "Cookie" describes?

**Comment by Konafets** [comment] 2017-03-04 08:58
@sagikazarmark @mtdowling We should consider to add a note to the README.md and/or the documentation about this.

> Dear reader, 
> if you miss the Cookie section in the documentation, check your browser add-ons first before you open an issue. It might be that one of them blocks the word `Cookie` and the whole section.

**Comment by SteveJobzniak** [comment] 2017-03-05 00:19
https://jsfiddle.net/7jrqnv5y/

![results](https://cloud.githubusercontent.com/assets/22373193/23583329/c24aa3b0-0141-11e7-9443-9719c7f531ee.png)

**Comment by SteveJobzniak** [comment] 2017-03-05 00:24
https://jsfiddle.net/7jrqnv5y/2/

![results2](https://cloud.githubusercontent.com/assets/22373193/23583353/7eadae08-0142-11e7-811a-5965fe771a0e.png)

**Comment by SteveJobzniak** [comment] 2017-03-05 00:27
From the above, the best solution seems to be to just rewrite the markup a little bit, to use an anchor with a name instead of another element with an "id", since ad-blockers target "id" but not "name":

```html
<a name="cookies" class="h1">Cookies</a>
<div id="cookies-section">text here...</a>
```

**Comment by Konafets** [comment] 2017-05-08 07:52
How do we want to proceed here?

1. Take the solution from @SteveJobzniak 
2. Add a hint to the documentation
3. Both

**Comment by sagikazarmark** [comment] 2017-05-08 13:12
I am not a huge fan of either of those TBH.

**Comment by SteveJobzniak** [comment] 2017-05-08 16:34
The <a> anchor name solution preserves all old links (#cookies) and is a valid way to write anchors. It existed in HTML before CSS IDs existed. So my vote goes to that solution.

**Comment by SteveJobzniak** [comment] 2017-05-08 23:26
@mtdowling Oh so it's a 3rd party doc generator...

Ehh, then I don't know what to do. They're unlikely to change markup just because your project has a "cookies" id/heading.

Perhaps add a notice about disabling adblocker while reading the docs to ensure the cookies section isn't hidden?

It would have to be a small info box at the top of the "Request Options" page to be seen.

The "cookies" link under Request Options goes nowhere since that whole section is killed by the adblocker, so it can't be put there... :\

**Comment by vlakoff** [comment] 2018-05-10 23:17
As a "least worst solution", how about adding a html comment?

Probably, a fraction of people encountering the issue would have a look at the html source, thus it would help reducing the amount of reports.

See https://github.com/sphinx-doc/sphinx/issues/2719 for the method to implement this.

**Closed** 2020-10-10 20:33 UTC
