### ISSUE TITLE
Using seek on message body stream doesn't work

### ISSUE THREAD

**Issue by AOndraSAN** [guzzle/guzzle#2142] opened 2018-09-12 13:42 UTC
| Q            | A
| ------------ | ---
| Bug?         | yes
| New Feature? | no
| Version      | 6.3.3

#### Actual Behavior

Using getContents() on the body stream does not rewind the pointer to the beginning of the stream before retrieving content.

If seeking cannot be performed on the stream, an error is supposed to be emitted, but it isn't. It is simply failing to seek.

#### Expected Behavior

Using getContents() on the body stream rewinds the pointer to the beginning of the stream before retrieving content.

#### Steps to Reproduce

As below, or casting the body to a string. It fails either way.

	$success = $request->getBody()->getContents(); // gets content
	$request->getBody()->rewind(); // for posterity
	$failure = $request->getBody()->getContents(); // doesn't get content
	$request->getBody()->rewind();

**Comment by sagikazarmark** [comment] 2018-09-12 13:46
`getContents` is NOT supposed to rewind a stream:

```
    /**
     * Returns the remaining contents in a string
     *
     * @return string
     * @throws \RuntimeException if unable to read.
     * @throws \RuntimeException if error occurs while reading.
     */
    public function getContents();
```

**Comment by AOndraSAN** [comment] 2018-09-12 13:56
The discussion I'd seen was that the PSR-7 standard dictated it wasn't supposed to rewind _after_ but _before_ was fine. It would appear that I did mix this up with `__toString()` but that _also_ does not work. Basically anything that involves seeking fails. Even running `rewind()` _before_ running `getContents()` fails.

**Comment by sagikazarmark** [comment] 2018-09-12 17:19
There might be some bugs somewhere, but I can't reproduce that issue (and frankly the PSR-7 test suite would probably broken as hell if what you're saying were true).

Here is an example: https://pastebin.com/Cb15Zge2

You can run it with:

`curl https://pastebin.com/raw/Cb15Zge2  | docker run --rm -i guzzle/guzzle php`

Can you try running Guzzle with the debug mode turned on? Can you provide some details about your environment?

**Comment by Nyholm** [comment] 2018-09-13 10:43
What kind of stream do you got? You may have a read-only non-seekable stream. If so, it makes sense. Can you give us a runnable example to reproduce this issue?

**Comment by AOndraSAN** [comment] 2018-10-01 18:49
I'm dealing with `GuzzleHttp\Psr7\LazyOpenStream`. Example:

```
$request = ServerRequest::fromGlobals();
$log->debug(strval($request->getBody())); // outputs content
$log->debug(strval($request->getBody())); // does not output content```

So is LazyOpenStream not seekable? I'm hitting a time wall trying to dig into your code for how streams are generated. Frankly this shouldn't be a concern unless I'm going out of my way to do something one-way for the sake of performance.

**Comment by Tobion** [comment] 2020-02-16 02:36
Closing as there is not much that can be done without a reproducer.

**Closed by Tobion** 2020-02-16 02:36 UTC
Labels: blocked/needs-response, kind/support

**Comment by jdart** [comment] 2022-11-25 17:20
I found it was possible to reproduce this but only when stepping over the seeking with xdebug, if I didn't have a breakpoint before the seeking it seemed fine.
