### ISSUE TITLE
Get the effective URL

### ISSUE THREAD

**Issue by dawehner** [guzzle/guzzle#1166] opened 2015-07-09 15:40 UTC
We (the drupal project, see https://www.drupal.org/node/2493911) try to update to guzzle 6,
especially in order to profit from the long term support.

The old code had \GuzzleHttp\Message\ResponseInterface::getEffectiveUrl which was pretty easy to use.
For guzzle 6 / PSR-7 this method seems to no longer exist.
As I saw there is the redirect middleware, but still, there is nothing to get out of it.

Note: Drupal currently stores the client on the container, in order to always use the same configuration.
This makes it harder to use some of the middlewares, like history, which might be useful to implement something as getEffectiveUrl.

My only thought was to implement an interface which extends ResponseInterface and somehow we wrap in a middleware the response to contain that URL.

Feedback or some general ideas would be great!

**Comment by Crell** [comment] 2015-07-09 16:41
This does seem to be a regression, since callers need to know if they should update their own records for a 301 (which is nominally what you're supposed to do).  I see 2 options:

1) Have them redirect middleware stick an X-EffectiveUrl header on it, or something, that people can check for.

2) As dawehner suggests, add:

```php
interface RedirectedResponseInterface extends ResponseInterface {
  public function getEffectiveUrl();
  public function getRedirectType();
}
```

And then the middleware, if there was a redirect, returns that instead of just a ResponseInterface.  Callers can then do:

```php
if ($response instanceof RedirectedResponseInterface && $response->getRedirectType() == 301) {
    // Update my database with $response->getEffectiveUrl();
}
```

I somewhat prefer option 2.

**Comment by dawehner** [comment] 2015-07-09 16:50
Redirect type is kinda pointless, isn't it? You already have the status code but yeah +1

**Comment by mtdowling** [comment] 2015-07-09 17:07
I don't think extending the response would be a great idea since the contract is that Guzzle returns a PSR-7 response; any middleware that modifies the return value to use a specific implementation of a PSR-7 response could be undone by another middleware that returns a different response object. i.e., there's no mandate that responses are chained using `with` methods, which means decorating would not solve the problem in a generic way.

I think the idea of adding a redirect header when a redirect is encountered is cool.

I also think this could be addressed by the feature request at https://github.com/guzzle/guzzle/issues/1152. A missing feature is to add a callback that is invoked when a handler has received a response and wants to notify the callback of transfer statistics, which could include the effectiveUri -- something like "on_stats" or "on_transfer", or something else. It would basically call the callback with `(RequestInterface $request, array $stats, ResponseInterface $response)`. I'm open to suggestions on the naming and implementation.

The callback idea works really well because a request can be redirected multiple times. Requests can be also be retried. This means that for any request there could be n number of effectiveUri changes while sending a request.

**Comment by Crell** [comment] 2015-07-09 17:13
I'm unclear how that callback would work/help in this case?  You mean like an "on_redirect" that has a callable that is called if the response also resulted in a redirect at some point?

```php
$client->send($request, [
  'on_redirect' => function($request, $response) { 
    // Update my database with something or other
  };
]);
```

Is that what you're talking about (give or take actual syntax)?

**Comment by mtdowling** [comment] 2015-07-09 17:22
Oh yeah, I think we could add an "on_redirect" callback as well, perhaps as a new option in the `allow_redirects` request option. Perhaps it could be more informative like `($originalRequest, $redirectRequest, $redirectResponse)`.

I was also wondering if something more generic could be added as a request option that is given either a hash of data containing handler specific data and some pre-defined Guzzle key value pairs, or perhaps an object that has a request, response, and getters for the data.

```php
$client->get('http://foo.com', [
    'on_transfer' => function (TransferData $trans) {
        echo $trans->getEffectiveUri();
        echo $trans->getRequest()->getUri();
        echo $trans->getResponse()->getStatusCode();
        var_dump($trans->getHandlerData());
    }
]);
```

Maybe that's a separate feature though... What do you think?

**Comment by mtdowling** [comment] 2015-07-10 03:04
The "on_transfer" can be a separate feature I think.

What do y'all think about https://github.com/guzzle/guzzle/pull/1167?

**Comment by yevgen-grytsay** [comment] 2015-07-12 12:45
Hello! I have similar problem. I use middleware to track requests in the redirect chain and save the last request's url. This works fine for synchronous requests: i perform request and then use my middleware to get the last request's url.

But i need to perform a lot of such requests asynchronously. I use \GuzzleHttp\Pool and 'fulfilled' callback. From within the callback i can refer the respone object but not the request. Is there a way to get the effective url of the asynchronous request?

**Comment by dawehner** [comment] 2015-07-17 11:13
@mtdowling 
We were discussing to track the history of redirects in the response headers, see https://www.drupal.org/node/2493911#comment-10128044
Do you think this would be worth to try out?

**Comment by dawehner** [comment] 2015-07-17 13:15
Tried to implement that, not sure whether its the proper way though at all: https://github.com/guzzle/guzzle/pull/1183

**Comment by mtdowling** [comment] 2015-07-30 03:51
This issue now resolved I think based on the fact that on_redirect was added. Adding something like on_transfer is being tracked here: https://github.com/guzzle/guzzle/issues/1152

Adding redirect history will be merged in once the PR is updated to use the same header name for each entry in the history. https://github.com/guzzle/guzzle/issues/1183

**Closed by mtdowling** 2015-07-30 03:51 UTC
Labels: Feature request

**Comment by tomsommer** [comment] 2015-08-13 11:57
It would be nice if there was a better way to get the final (effective) URL, and not have to pull the data out of a callback function (with a global). ->getEffectiveUrl() was a great feature, and on_redirect makes it hard to emulate it.
