### ISSUE TITLE
Request query overriding client query

### ISSUE THREAD

**Issue by AliceLoeser** [guzzle/guzzle#1698] opened 2016-12-22 13:43 UTC
Hello,

When declaring a query in the client declaration, like so:
```
$client = new GuzzleHttp\Client(array(
                'base_uri'      => 'http://api',
                'query'         => array(
                    'access_token'  => 'token',
                )
            )
        );
```
It does work and uses the query parameters.
The issue is that when declaring request object with query parameters, they override the client's query parameters. 
Example:
`$response = $this->client->request('GET','endpoint',['query' => ['count' => 1]]);`
The request loses the parameter 'access_token' that was defined in the client. To make it work, it is required to pass access_token again like so:
` $response = $this->client->request('GET','endpoing',['query' => ['count' => 1, 'access_token' => 'token']]);`

**Comment by sagikazarmark** [comment] 2016-12-22 18:07
Duplicate of https://github.com/guzzle/guzzle/issues/1452

**Closed by sagikazarmark** 2016-12-22 18:07 UTC
Labels: Question
