### ISSUE TITLE
InvalidArgumentException when posting integers and booleans

### ISSUE THREAD

**Issue by kmorozov** [guzzle/guzzle#1447] opened 2016-04-07 21:17 UTC
When I send integers and booleans via the multipart upload I get the error "Invalid resource type: integer". It looks like this issue has come up before (#628) but was never merged. I encountered it on 6.2.0.

Changing stream_for like so seems to fix it:
````php
function stream_for($resource = '', array $options = []){
switch (gettype($resource)) {
        case 'string':
        case 'integer': // added
            $stream = fopen('php://temp', 'r+');
            if ($resource !== '') {
                fwrite($stream, $resource);
                fseek($stream, 0);
//...
````

**Comment by mtdowling** [comment] 2016-04-08 22:31
Duplicate of and fixed by https://github.com/guzzle/psr7/pull/46. Perhaps you can fork that PR and add the missing tests to help that PR along?

**Closed by mtdowling** 2016-04-08 22:31 UTC
