### ISSUE TITLE
Getting Uncaught GuzzleHttp\Exception\RequestException: cURL error 60: SSL certificate problem: certificate has expired (see http://curl.haxx.se/libcurl/c/libcurl-errors.html) 

### ISSUE THREAD

**Issue by rajkumargohan** [guzzle/guzzle#2578] opened 2020-02-03 18:43 UTC
**Guzzle version(s) affected**: 6.3
**PHP version**: 7.1.33
**cURL version**: 7.66.0

**Description**  
When I tried to send a normal request, I am not getting any issue. But when I tried to send a file with form data, I am getting below issue

![image](https://user-images.githubusercontent.com/6098014/73680813-f8444b80-46e2-11ea-80c7-a06a48b277b6.png)

**How to reproduce**  
Try to upload a file with form data

**Comment by mfn** [comment] 2020-02-04 08:35
To possible problems here, but neither are IMHO related to Guzzle:
- either the remote servers certificate is expired (can you open that host in the browser without getting a security warning?)
- or (maybe) the local certificate chain is outdated.

**Comment by rajkumargohan** [comment] 2020-02-04 08:38
Hi @mfn,
I don't get any security warning on the server where I post the request.
When I posted the normal form data, I am not getting any issue. But when I post data with files, I am getting this issue. I am looking for solutions... I will post it if I found any.

**Comment by mfn** [comment] 2020-02-04 09:20
Maybe your code is using a different host for uploading bigger files? That's not uncommon, some platforms do that.

**Comment by rajkumargohan** [comment] 2020-02-04 09:36
I am uploading small files. Script used to work for more than 3 months. It stopped suddenly since yesterday and return that error.

**Comment by alexeyshockov** [comment] 2020-02-04 11:10
@rajkumargohan, do you use any Guzzle certificate-related options in your request? If no, then it's definitely not Guzzle related, and you should start with checking your certificate chain (as @mfn suggested).

I'm closing this one, because it doesn't look like a Guzzle bug. Please ask your question (better with more details) on StackOverflow please, it's a better place for general questions like this.

Closing this one for now. Feel free to reopen with more info (a reproducible example is appreciated, it's really hard to guess something without one).

**Closed by alexeyshockov** 2020-02-04 11:10 UTC

**Comment by mfn** [comment] 2020-02-04 16:10
>  It stopped suddenly since yesterday and return that error.

That's indicator that the certificate expired.
