### ISSUE TITLE
if remote image not exist sink storing empty image on disk

### ISSUE THREAD

**Issue by rajjanorkar** [guzzle/guzzle#2022] opened 2018-03-08 14:26 UTC
| Q            | A
| ------------ | ---
| Bug?         yes
| New Feature? no
| Version      6.3

#### Actual Behavior

I am trying to get the website favicon image, if website have favicon image then it works fine and it store the image correctly.

It is storing empty image on disk when website favicon is not present. Actually it should not store anything on disk if remote image is not exist what you think?

```
       // try to get domain/favicon.ico
        if (isset($urlElements['scheme']) && isset($urlElements['host'])) {
            $url = $urlElements['scheme'] . '://' . $urlElements['host'] . '/favicon.ico';

            try {
                // get the image extension
                $imageName = 'icon-' . str_random(32) . '.png';
                // full image location
                $imagePath = '/images/' . $imageName;

                $stream = fopen($imagePath, 'w');
                //guzzle get() and sink into resource
                $this->guzzleClient->get($url, ['sink' => $stream]);

                // return feeds fevicon
                return $imageName;
            } catch (Exception $e) {
               // Error in while storing fevicon to Disk.
                return null;
            }
        }

```

#### Expected Behavior

When remote image is not present then it should not store empty image on disk.

#### Steps to Reproduce
Please have look at above code to reproduce the issue and use any remote url which does not have image.

**Comment by stickypages** [comment] 2018-03-09 23:06
Yeah I just noticed this too. Unless you call the URL twice... ideally it wouldn't created the file if it doesn't return 200. 

```
$client = new GuzzleHttp\Client();
		$res = $client->request('GET', $fromUrl);

		if($res->getStatusCode() === 200) {
			$res = $client->request('GET', $fromUrl, ['sink' => $newFile]);
			if($res->getStatusCode() === 200) {
				return $newFile;
			}
			return false;
		}
```

**Comment by Nyholm** [comment] 2018-03-16 06:09
Im not sure this is a bug. You put the response into the sink. 

Why would you assume all users always want the 200 response? 

@rajjanorkar Maybe it would be simpler to not use the `sink`? Like you fetch the response, validate the response code and then choose to save it or not. @stickypages suggestion does also work. 

Im closing this since it is not a bug with guzzle.

**Closed by Nyholm** 2018-03-16 06:09 UTC

**Comment by stickypages** [comment] 2018-03-16 21:54
@Nyholm I agree it's not directly a bug. 

Although some additional features would be nice here. Calling the URL **twice** is not efficient with resources. Can we place a feature along with the 'sink', IF request is 200, write the file. Otherwise don't. 

As of right now, it will write to a file no matter what... If we could place a feature on that, it would be incredible. 

Thoughts on that?

**Comment by kgrozdanovski** [comment] 2022-01-04 11:06
This should be reopened. It is a very serious issue since you cannot validate a response/HTTP status code if you are using a sink.

**Comment by mfn** [comment] 2022-01-04 11:22
I can follow you argument but I suggest to create a new issue: even the original example is clear to always have a file created because _this happens in user space_ already, outside guzzle (the `fopen` call already does this).

I would bet more is needed to handle this and prevent double-fetch attempts etc.
